CREATE TABLE `actual_state` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`character_id` integer NOT NULL,
	`egratinure_current` integer DEFAULT 0 NOT NULL,
	`legere_current` integer DEFAULT 0 NOT NULL,
	`grave_current` integer DEFAULT 0 NOT NULL,
	`fatale_current` integer DEFAULT 0 NOT NULL,
	`mort_current` integer DEFAULT 0 NOT NULL,
	`maitrise_current` integer DEFAULT 0 NOT NULL,
	`chance_current` integer DEFAULT 0 NOT NULL,
	`conditions` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`character_id`) REFERENCES `characters`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `characters` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`nom` text DEFAULT '' NOT NULL,
	`concept` text DEFAULT '' NOT NULL,
	`dragon` integer DEFAULT 0 NOT NULL,
	`dragon_sub` integer DEFAULT 0 NOT NULL,
	`fatalite` integer DEFAULT 0 NOT NULL,
	`fatalite_sub` integer DEFAULT 0 NOT NULL,
	`homme` integer DEFAULT 0 NOT NULL,
	`homme_sub` integer DEFAULT 0 NOT NULL,
	`force` integer DEFAULT 0 NOT NULL,
	`resistance` integer DEFAULT 0 NOT NULL,
	`intelligence` integer DEFAULT 0 NOT NULL,
	`volonte` integer DEFAULT 0 NOT NULL,
	`coordination` integer DEFAULT 0 NOT NULL,
	`perception` integer DEFAULT 0 NOT NULL,
	`presence` integer DEFAULT 0 NOT NULL,
	`empathie` integer DEFAULT 0 NOT NULL,
	`physique` integer DEFAULT 0 NOT NULL,
	`mental` integer DEFAULT 0 NOT NULL,
	`manuel` integer DEFAULT 0 NOT NULL,
	`social` integer DEFAULT 0 NOT NULL,
	`egratinure_max` integer DEFAULT 0 NOT NULL,
	`legere_max` integer DEFAULT 0 NOT NULL,
	`grave_max` integer DEFAULT 0 NOT NULL,
	`fatale_max` integer DEFAULT 0 NOT NULL,
	`mort_max` integer DEFAULT 0 NOT NULL,
	`maitrise_max` integer DEFAULT 0 NOT NULL,
	`chance_max` integer DEFAULT 0 NOT NULL,
	`biographie` text DEFAULT '' NOT NULL,
	CONSTRAINT "dragon_sub_range" CHECK(dragon_sub >= 0 AND dragon_sub <= 10),
	CONSTRAINT "fatalite_sub_range" CHECK(fatalite_sub >= 0 AND fatalite_sub <= 10),
	CONSTRAINT "homme_sub_range" CHECK(homme_sub >= 0 AND homme_sub <= 10)
);
