// GENERATED by scripts/build-catalogs.ts from data-src/archetypes.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { ArchetypePreset } from './archetype-catalog';

export const ARCHETYPE_CATALOG_DATA: ArchetypePreset[] = [
  {
    "id": "artisan",
    "caste": "artisan",
    "data": {
      "name": "Artisan",
      "concept": "Artisan de métier, formé à l'atelier",
      "stats": {
        "force": 3,
        "resistance": 3,
        "intelligence": 4,
        "volonte": 3,
        "coordination": 5,
        "perception": 4,
        "presence": 3,
        "empathie": 3,
        "physique": 2,
        "mental": 3,
        "manuel": 4,
        "social": 2,
        "maitriseMax": 3,
        "chanceMax": 3
      },
      "skills": [
        {
          "name": "Artisanat",
          "attribut": "manuel",
          "value": 3
        },
        {
          "name": "Matières premières",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Estimation",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Conception",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Marchandage",
          "attribut": "social",
          "value": 2
        }
      ],
      "option": {
        "key": "specialite",
        "label": "Spécialité",
        "value": 4,
        "choices": [
          "Artisanat",
          "Artisanat élémentaire",
          "Conception",
          "Contrefaçon",
          "Don artistique"
        ]
      }
    }
  },
  {
    "id": "combattant",
    "caste": "combattant",
    "data": {
      "name": "Combattant",
      "concept": "Homme d'armes entraîné à la guerre",
      "stats": {
        "force": 5,
        "resistance": 5,
        "intelligence": 3,
        "volonte": 4,
        "coordination": 4,
        "perception": 3,
        "presence": 3,
        "empathie": 2,
        "physique": 4,
        "mental": 2,
        "manuel": 3,
        "social": 2,
        "maitriseMax": 4,
        "chanceMax": 2
      },
      "skills": [
        {
          "name": "Esquive",
          "attribut": "physique",
          "value": 3
        },
        {
          "name": "Athlétisme",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Bouclier",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Intimidation",
          "attribut": "social",
          "value": 2
        },
        {
          "name": "Premiers soins",
          "attribut": "mental",
          "value": 1
        }
      ],
      "option": {
        "key": "arme-de-predilection",
        "label": "Arme de prédilection",
        "value": 4,
        "choices": [
          "Armes tranchantes",
          "Armes de choc",
          "Armes contondantes",
          "Armes d'hast",
          "Armes à projectiles",
          "Corps à corps"
        ]
      }
    }
  },
  {
    "id": "commercant",
    "caste": "commercant",
    "data": {
      "name": "Commerçant",
      "concept": "Marchand rompu au négoce et aux routes",
      "stats": {
        "force": 2,
        "resistance": 3,
        "intelligence": 4,
        "volonte": 3,
        "coordination": 3,
        "perception": 4,
        "presence": 5,
        "empathie": 4,
        "physique": 2,
        "mental": 3,
        "manuel": 2,
        "social": 4,
        "maitriseMax": 3,
        "chanceMax": 3
      },
      "skills": [
        {
          "name": "Marchandage",
          "attribut": "social",
          "value": 4
        },
        {
          "name": "Estimation",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Baratin",
          "attribut": "social",
          "value": 2
        },
        {
          "name": "Psychologie",
          "attribut": "social",
          "value": 2
        },
        {
          "name": "Lire et écrire",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Vie en cité",
          "attribut": "mental",
          "value": 2
        }
      ],
      "option": null
    }
  },
  {
    "id": "erudit",
    "caste": "erudit",
    "data": {
      "name": "Érudit",
      "concept": "Lettré au service d'une bibliothèque ou d'un seigneur",
      "stats": {
        "force": 2,
        "resistance": 2,
        "intelligence": 5,
        "volonte": 4,
        "coordination": 3,
        "perception": 4,
        "presence": 3,
        "empathie": 3,
        "physique": 1,
        "mental": 4,
        "manuel": 2,
        "social": 3,
        "maitriseMax": 3,
        "chanceMax": 3
      },
      "skills": [
        {
          "name": "Lire et écrire",
          "attribut": "mental",
          "value": 4
        },
        {
          "name": "Astrologie",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Médecine",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Connaissance de la magie",
          "attribut": "mental",
          "value": 2
        }
      ],
      "option": {
        "key": "domaine-d-etude",
        "label": "Domaine d'étude",
        "value": 4,
        "choices": [
          "Histoire",
          "Lois",
          "Géographie",
          "Connaissance des dragons",
          "Connaissance de la magie",
          "Médecine"
        ]
      }
    }
  },
  {
    "id": "mage",
    "caste": "mage",
    "data": {
      "name": "Mage",
      "concept": "Praticien de la magie formé aux disciplines",
      "stats": {
        "force": 2,
        "resistance": 3,
        "intelligence": 5,
        "volonte": 5,
        "coordination": 3,
        "perception": 4,
        "presence": 4,
        "empathie": 3,
        "physique": 1,
        "mental": 4,
        "manuel": 2,
        "social": 3,
        "maitriseMax": 4,
        "chanceMax": 3
      },
      "skills": [
        {
          "name": "Connaissance de la magie",
          "attribut": "mental",
          "value": 4
        },
        {
          "name": "Lire et écrire",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Astrologie",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Herboristerie",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Eloquence",
          "attribut": "social",
          "value": 2
        }
      ],
      "option": null
    }
  },
  {
    "id": "prodige",
    "caste": "prodige",
    "data": {
      "name": "Prodige",
      "concept": "Représentant du Grand Dragon de la Nature",
      "stats": {
        "force": 3,
        "resistance": 4,
        "intelligence": 4,
        "volonte": 5,
        "coordination": 3,
        "perception": 4,
        "presence": 4,
        "empathie": 4,
        "physique": 3,
        "mental": 3,
        "manuel": 2,
        "social": 3,
        "maitriseMax": 3,
        "chanceMax": 4
      },
      "skills": [
        {
          "name": "Connaissance des animaux",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Survie",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Herboristerie",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Dressage",
          "attribut": "social",
          "value": 2
        },
        {
          "name": "Connaissance de la magie",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Premiers soins",
          "attribut": "mental",
          "value": 2
        }
      ],
      "option": null
    }
  },
  {
    "id": "protecteur",
    "caste": "protecteur",
    "data": {
      "name": "Protecteur",
      "concept": "Garde assermenté, bouclier des siens",
      "stats": {
        "force": 4,
        "resistance": 5,
        "intelligence": 3,
        "volonte": 4,
        "coordination": 4,
        "perception": 4,
        "presence": 4,
        "empathie": 3,
        "physique": 4,
        "mental": 2,
        "manuel": 2,
        "social": 3,
        "maitriseMax": 4,
        "chanceMax": 2
      },
      "skills": [
        {
          "name": "Corps à corps",
          "attribut": "physique",
          "value": 3
        },
        {
          "name": "Bouclier",
          "attribut": "physique",
          "value": 3
        },
        {
          "name": "Esquive",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Commandement",
          "attribut": "social",
          "value": 2
        },
        {
          "name": "Premiers soins",
          "attribut": "mental",
          "value": 2
        },
        {
          "name": "Psychologie",
          "attribut": "social",
          "value": 2
        }
      ],
      "option": {
        "key": "arme-de-predilection",
        "label": "Arme de prédilection",
        "value": 3,
        "choices": [
          "Armes tranchantes",
          "Armes contondantes",
          "Armes d'hast",
          "Armes de jet",
          "Corps à corps"
        ]
      }
    }
  },
  {
    "id": "voyageur",
    "caste": "voyageur",
    "data": {
      "name": "Voyageur",
      "concept": "Coureur de routes, guide et éclaireur",
      "stats": {
        "force": 3,
        "resistance": 4,
        "intelligence": 3,
        "volonte": 4,
        "coordination": 4,
        "perception": 5,
        "presence": 3,
        "empathie": 3,
        "physique": 3,
        "mental": 3,
        "manuel": 3,
        "social": 2,
        "maitriseMax": 3,
        "chanceMax": 4
      },
      "skills": [
        {
          "name": "Survie",
          "attribut": "mental",
          "value": 4
        },
        {
          "name": "Orientation",
          "attribut": "mental",
          "value": 3
        },
        {
          "name": "Pister",
          "attribut": "manuel",
          "value": 2
        },
        {
          "name": "Escalade",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Natation",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Equitation",
          "attribut": "physique",
          "value": 2
        },
        {
          "name": "Géographie",
          "attribut": "mental",
          "value": 2
        }
      ],
      "option": null
    }
  }
];
