// GENERATED by scripts/build-catalogs.ts from data-src/armor.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { ArmorPreset } from './armor-catalog';

export const ARMOR_CATALOG_DATA: ArmorPreset[] = [
  {
    "id": "vetements-epais",
    "category": "Armures légères",
    "data": {
      "name": "Vêtements épais",
      "defenseMax": 2,
      "prerequisites": "",
      "creationDifficulty": 10,
      "creationTime": 4,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "fourrures",
    "category": "Armures légères",
    "data": {
      "name": "Fourrures",
      "defenseMax": 5,
      "prerequisites": "",
      "creationDifficulty": 10,
      "creationTime": 5,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "cuir-souple",
    "category": "Armures légères",
    "data": {
      "name": "Cuir souple",
      "defenseMax": 4,
      "prerequisites": "",
      "creationDifficulty": 15,
      "creationTime": 8,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "cuir-cloute",
    "category": "Armures légères",
    "data": {
      "name": "Cuir clouté",
      "defenseMax": 6,
      "prerequisites": "",
      "creationDifficulty": 15,
      "creationTime": 10,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "cuir-bouilli",
    "category": "Armures légères",
    "data": {
      "name": "Cuir bouilli",
      "defenseMax": 8,
      "prerequisites": "",
      "creationDifficulty": 20,
      "creationTime": 12,
      "encombrementMalus": -2,
      "special": ""
    }
  },
  {
    "id": "armure-os-corne",
    "category": "Armures moyennes",
    "data": {
      "name": "Armure d'os et de corne",
      "defenseMax": 12,
      "prerequisites": "FOR 4",
      "creationDifficulty": 20,
      "creationTime": 20,
      "encombrementMalus": -2,
      "special": ""
    }
  },
  {
    "id": "cotte-legere",
    "category": "Armures moyennes",
    "data": {
      "name": "Cotte légère",
      "defenseMax": 10,
      "prerequisites": "FOR 4",
      "creationDifficulty": 15,
      "creationTime": 15,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "cotte-mailles",
    "category": "Armures moyennes",
    "data": {
      "name": "Cotte de mailles",
      "defenseMax": 15,
      "prerequisites": "FOR 4, RES 6",
      "creationDifficulty": 20,
      "creationTime": 25,
      "encombrementMalus": -2,
      "special": ""
    }
  },
  {
    "id": "armure-anneaux",
    "category": "Armures moyennes",
    "data": {
      "name": "Armure d'anneaux",
      "defenseMax": 16,
      "prerequisites": "FOR 4, RES 5",
      "creationDifficulty": 15,
      "creationTime": 30,
      "encombrementMalus": -4,
      "special": ""
    }
  },
  {
    "id": "brigandine",
    "category": "Armures moyennes",
    "data": {
      "name": "Brigandine",
      "defenseMax": 17,
      "prerequisites": "FOR 5, RES 5",
      "creationDifficulty": 20,
      "creationTime": 20,
      "encombrementMalus": -5,
      "special": ""
    }
  },
  {
    "id": "armure-ecaille",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure d'écailles",
      "defenseMax": 20,
      "prerequisites": "FOR 6, RES 6",
      "creationDifficulty": 20,
      "creationTime": 30,
      "encombrementMalus": -5,
      "special": ""
    }
  },
  {
    "id": "armure-bois",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure de bois",
      "defenseMax": 15,
      "prerequisites": "FOR 4, RES 3",
      "creationDifficulty": 20,
      "creationTime": 15,
      "encombrementMalus": -6,
      "special": ""
    }
  },
  {
    "id": "armure-demi-plaques",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure de demi-plaques",
      "defenseMax": 18,
      "prerequisites": "FOR 4, RES 5",
      "creationDifficulty": 20,
      "creationTime": 25,
      "encombrementMalus": -6,
      "special": ""
    }
  },
  {
    "id": "armure-lamelles",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure de lamelles",
      "defenseMax": 22,
      "prerequisites": "FOR 5, RES 5",
      "creationDifficulty": 20,
      "creationTime": 30,
      "encombrementMalus": -8,
      "special": ""
    }
  },
  {
    "id": "armure-plaques",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure de plaques",
      "defenseMax": 25,
      "prerequisites": "FOR 6, RES 7",
      "creationDifficulty": 25,
      "creationTime": 40,
      "encombrementMalus": -10,
      "special": ""
    }
  },
  {
    "id": "armure-draconique",
    "category": "Armures lourdes",
    "data": {
      "name": "Armure draconique",
      "defenseMax": 27,
      "prerequisites": "FOR 7, RES 7",
      "creationDifficulty": 25,
      "creationTime": 10,
      "encombrementMalus": -10,
      "special": ""
    }
  }
];
