// GENERATED by scripts/build-catalogs.ts from data-src/manoeuvres.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { ManoeuvrePreset } from './manoeuvre-catalog';

export const MANOEUVRE_CATALOG_DATA: ManoeuvrePreset[] = [
  {
    "id": "melee-attaque-simple",
    "contexte": "melee",
    "famille": "offensive",
    "nom": "Attaque simple",
    "stats": {
      "difficulty": {
        "value": 15
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "normaux"
    },
    "inGameEffect": "Aucun effet particulier.",
    "description": "L'attaquant ne cherche aucun effet particulier et veut juste toucher son adversaire."
  },
  {
    "id": "melee-attaque-brutale",
    "contexte": "melee",
    "famille": "offensive",
    "nom": "Attaque brutale",
    "stats": {
      "difficulty": {
        "value": 15
      },
      "dodge": {
        "key": "facile",
        "value": 10
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "la Force s'ajoute aux dommages"
    },
    "inGameEffect": "La Force s'ajoute aux dommages ; deux fois avec une arme à deux mains. Esquive facilitée (10).",
    "description": "L'attaquant privilégie la force à la précision pour porter une attaque violente, mais plus facilement prévisible par son adversaire.\nSi l'attaquant utilise une arme à deux mains, sa Force s'ajoute deux fois au lieu d'une."
  },
  {
    "id": "melee-attaque-precise",
    "contexte": "melee",
    "famille": "offensive",
    "nom": "Attaque précise",
    "stats": {
      "difficulty": {
        "value": 15,
        "plusX": true
      },
      "dodge": {
        "value": 15,
        "plusX": true
      },
      "parry": {
        "value": 15,
        "plusX": true
      },
      "damage": "normaux, -X à l'Indice de protection"
    },
    "inGameEffect": "L'attaquant choisit X : +X à la Difficulté de l'attaque, de l'esquive et de la parade. Si le coup porte, l'Indice de protection de l'armure du défenseur est réduit de X. Le meneur de jeu peut l'interdire contre une armure sans faille.",
    "description": "L'attaquant s'impose une Difficulté supplémentaire (X) pour viser une zone ou une partie de l'armure qui lui semble moins protégée. Le meneur de jeu peut interdire l'utilisation de cette attaque s'il estime que l'armure de l'adversaire ne comporte pas la moindre faille - mais de telles armures sont vraiment très rares... Si le coup porte, l'Indice de protection de l'armure du défenseur est réduit de X."
  },
  {
    "id": "melee-actions-defensives",
    "contexte": "melee",
    "famille": "defensive",
    "nom": "Les actions défensives",
    "inGameEffect": "Si l'attaque et la parade sont réussies sans NR, le défenseur n'est pas touché.",
    "description": "Les actions défensives sont de deux types : soit le défenseur cherche à bloquer l'arme avec la sienne ou un bouclier avant qu'elle ne le touche (parade) ou il va tenter de se mettre hors de portée du coup (esquive). Les actions défensives sont toujours en faveur du défenseur. Si l'attaque et la parade sont réussies sans NR, le défenseur n'est pas touché."
  },
  {
    "id": "melee-parade",
    "contexte": "melee",
    "famille": "defensive",
    "nom": "La parade",
    "inGameEffect": "Difficulté 15. Réussie si le défenseur obtient au moins autant de NR que l'attaquant : aucun dommage. Coûte un dé d'action non utilisé. Avec 2 NR de plus que l'attaquant : riposte gratuite (attaque simple, dommages réduits d'un dé), une par tour, jamais en parant une riposte. Les armes de corps à corps ou de jet ne parent pas une arme de mêlée.",
    "description": "Parer un coup nécessite de posséder une arme adéquate et solide pour l'interposer sur la trajectoire de l'arme attaquante. En règle générale, les armes de corps à corps ou de jet (comme les dagues) ne peuvent jamais servir à parer une arme de mêlée. Le meneur de jeu peut décider d'exceptions s'il le désire. Une parade a une Difficulté de base de 15 et elle est réussie si le défenseur obtient au moins autant de NR que l'attaquant. Dans ce cas, aucun dommage n'est infligé. Une parade impose de dépenser un dé d'action (n'importe lequel) parmi ceux encore non utilisés au moment de l'attaque ennemie. Si le défenseur les a tous utilisés, il ne peut pas parer.\nExemple : un attaquant va toucher avec un NR. Le défenseur pare et obtient un NR. Il n'est pas touché. S'il n'avait pas eu ce NR, il aurait été touché et l'attaquant aurait disposé d'un NR pour calculer ses dommages (voir plus loin).\nSi le défenseur obtient deux NR de plus que son agresseur, il peut tenter immédiatement une riposte. Une riposte est une attaque gratuite ne coûtant aucune action. Elle subit les malus d'éventuelles attaques préliminaires dans le tour mais n'en entraînera aucun. Une riposte est toujours une attaque simple dont les dommages sont réduits d'un dé. Une seule riposte est possible par tour et il est impossible de riposter en parant une riposte."
  },
  {
    "id": "melee-esquive",
    "contexte": "melee",
    "famille": "defensive",
    "nom": "L'esquive",
    "inGameEffect": "Difficulté 15. Les NR obtenus sont soustraits aux NR de l'attaquant. Coûte un dé d'action non utilisé. Avec plus de NR que l'attaquant : le défenseur garde ses NR de « recul » jusqu'à la fin du tour (perdus s'il est touché), chacun +1 à un dé d'Initiative.",
    "description": "Esquiver un coup consiste à se reculer ou à se détourner pour éviter que l'arme ne le touche. L'esquive ne nécessite qu'un peu de place pour avoir la liberté de ses mouvements (esquiver dans la foule ou dans un cul-de-sac est peu évident). Une esquive peut être partielle. En effet, il sera toujours utile de réussir à protéger ses zones vitales même si un coup touche. La Difficulté de base d'une esquive est de 15. Tous les NR obtenus sont soustraits aux NR de l'attaquant. Une esquive impose de dépenser un dé d'action (n'importe lequel) parmi ceux encore non utilisés au moment de l'attaque ennemie. Si le défenseur les a tous utilisés, il ne peut pas esquiver.\nExemple : un attaquant va toucher avec deux NR. Le défenseur esquive et obtient un NR. Il est tout de même touché mais l'attaquant ne dispose que d'un NR pour calculer ses dommages (voir plus loin). Si le défenseur en avait obtenu deux, il aurait entièrement évité le coup.\nSi un défenseur obtient plus de NR que son adversaire, il s'écarte de son agresseur et peut reprendre du champ pour se replacer. Dans ce cas, il retient le nombre de NR qu'il a obtenu en esquive durant le tour. S'il est touché avant la fin du tour, il perd ces NR de \"recul\". Ces NR constituent chacun un bonus de +1 que le personnage pourra appliquer à un ou plusieurs dés d'Initiative pour en augmenter la valeur."
  },
  {
    "id": "melee-utiliser-un-bouclier",
    "contexte": "melee",
    "famille": "defensive",
    "nom": "Utiliser un bouclier",
    "inGameEffect": "Parer : l'Indice de protection du bouclier devient un bonus de parade (coûte un dé d'action). Ou protection statique, sans parer : son Indice de protection s'ajoute à l'armure.",
    "description": "Un bouclier peut s'utiliser de deux façons :\n• Soit son porteur l'utilise pour parer et l'Indice de protection devient alors un bonus de parade. L'action est alors résolue comme une parade normale. Une parade impose de dépenser un dé d'action (n'importe lequel) parmi ceux encore non utilisés au moment de l'attaque ennemie. Si le défenseur les a tous utilisés, il ne peut pas parer.\n• Soit son porteur l'utilise pour se protéger de façon statique (et donc sans parer), auquel cas son Indice de protection s'ajoute à l'armure."
  },
  {
    "id": "melee-usure-des-armes",
    "contexte": "melee",
    "famille": "defensive",
    "nom": "L'usure des armes",
    "inGameEffect": "Parer une attaque critique brise l'arme du défenseur si elle est de qualité inférieure à celle de l'attaquant ; la parade compte quand même.",
    "description": "Les armes de Kor sont parfois de qualité inégale et il arrive qu'une passe d'armes particulièrement violente se termine par la rupture d'une lame ou d'un manche. Lorsqu'une arme est utilisée pour parer une attaque critique, l'arme du défenseur se brise si elle est d'une qualité inférieure à celle de l'attaquant. Toutefois, la parade a lieu et ses effets sont pris en compte normalement. Une arme brisée peut être réparée selon les règles décrites à la page 148."
  },
  {
    "id": "melee-armes-improvisees",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Armes improvisées",
    "stats": {
      "difficulty": {
        "value": 20
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "selon",
        "note": "l'arme"
      },
      "damage": "variables"
    },
    "inGameEffect": "Attaque sur Coordination (objet maniable) ou Force (objet lourd ou encombrant). Toute parade risque de briser l'objet.",
    "description": "Il est possible qu'un combattant se voit contraint de saisir une arme de fortune pour se défendre (lors d'une rixe d'auberge, par exemple). Comme il y a peu de chance pour qu'il ait développé la Compétence Tabouret ou Cruche de vin, il subit une pénalité qui explique en fait la Difficulté de ses actions. Ensuite, ses jets d'attaque doivent être effectués avec Coordination, s'il s'agit d'un objet maniable, ou avec Force s'il s'empare d'un banc ou de tout objet particulièrement lourd ou encombrant. Une valeur de dommages de base peut être attribuée à cette arme de fortune mais, généralement, il est peu probable qu'une arme improvisée inflige de véritables blessures. De plus, toute parade effectuée avec cette arme risque de briser l'objet."
  },
  {
    "id": "melee-assommer",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Assommer",
    "stats": {
      "difficulty": {
        "value": 20
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "possibles"
    },
    "inGameEffect": "Défense ratée : la victime jette Physique + Résistance contre les dommages infligés (l'attaquant peut n'utiliser qu'une partie de ses NR). Raté : sonnée 1D10 tours, Difficultés +10. Raté même contre la moitié (arrondi inférieur) : assommée 2D10 tours et subit les dommages.",
    "description": "Pour assommer son adversaire, l'attaquant peut utiliser n'importe quel type d'attaque.\nSi elle rate son action de défense, la victime doit effectuer un jet de Physique + Résistance contre une Difficulté égale aux dommages infligés pour éviter d'être assommé. S'il le désire l'attaquant ne peut utiliser qu'une partie de ses NR pour calculer ses dommages. Si le jet est raté, la victime est sonnée pour 1D10 tours et toutes ses actions voient leur Difficulté augmenter de 10 durant ce délai. Si le jet est raté même contre la moitié de la Difficulté (arrondi à l'inférieur), la victime est assommée pour 2D10 tours et subit les dommages."
  },
  {
    "id": "melee-attaques-deroutantes",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Attaques déroutantes",
    "stats": {
      "difficulty": {
        "key": "variable"
      },
      "dodge": {
        "key": "variable"
      },
      "parry": {
        "key": "variable"
      },
      "damage": "variables"
    },
    "inGameEffect": "Jet contre une Difficulté de base (généralement 15) modifiée selon les conditions, puis jet d'opposition possible : les NR deviennent des malus sur le jet adverse. Sable : Physique + Coordination (15) pour le ramasser, puis Manuel + Coordination (20) pour le lancer ; l'adversaire esquive à Difficulté + 5 ou est aveuglé 1 tour + 1 par NR (Difficultés +10).",
    "description": "Il n'est pas rare de voir deux adversaires se lancer du sable à la figure, se cacher derrière un arbre pour se gêner mutuellement ou se servir de leurs épées comme d'un projectile meurtrier. La règle est la suivante : le personnage qui fait l'action effectue un jet contre une Difficulté de base (généralement 15) qui peut être modifiée par des bonus/malus en fonction des conditions. Ensuite, un jet d'opposition peut départager les deux protagonistes et les NR peuvent se transformer en malus sur le jet adverse.\nPar exemple, si un combattant utilise un arbre pour gêner son adversaire, il doit effectuer un jet de Physique + Athlétisme contre une Difficulté de 15. Ses NR deviendront des malus de 1 pour l'adversaire qui, en raison de la gêne, verra la Difficulté de ses coups augmenter.\nPour lancer du sable, il faut effectuer un premier jet de Physique + Coordination contre une Difficulté de 15 (pour se baisser et ramasser le sable), puis un jet de Manuel + Coordination contre une Difficulté de 20 (15 de base + 5 pour la visée) pour le lancer dans les yeux de son adversaire. Si le premier jet est raté, le défenseur subit le malus de \"combat au sol\" pour la prochaine attaque de son adversaire. Si le lancer est réussi, l'adversaire peut tenter une esquive à Difficulté + 5 ou se retrouver aveuglé pendant un tour, plus 1 par NR du lanceur. Une fois aveuglé, le défenseur voit la Difficulté de tous ses jets augmenter de 10."
  },
  {
    "id": "melee-charger",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Charger",
    "stats": {
      "difficulty": {
        "value": 10
      },
      "dodge": {
        "key": "selon",
        "note": "l'élan"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "la Force s'ajoute aux dommages"
    },
    "inGameEffect": "1 action d'élan : esquive facile (10), renversement automatique à +5 si la charge touche. 2 actions d'élan : esquive évidente (5), renversement à +10. À cheval, la Force de la monture remplace celle du cavalier. Un défenseur qui esquive avec 2 NR peut riposter.",
    "description": "L'attaquant se rue sur son adversaire avec toute la hargne dont il dispose. La charge dépend du nombre d'actions passées par l'attaquant à prendre de l'élan.\n• 1 action d'élan : esquive facile (10), action automatique de renversement avec un bonus de +5 en cas de toucher.\n• 2 actions d'élan : esquive évidente (5), action automatique de renversement avec un bonus de +10 en cas de toucher.\nDans le cas d'une charge à cheval, la Force de la monture se substitue à celle du cavalier (cf. page 188).\nSi le défenseur parvient à esquiver avec 2 NR, il peut effectuer une riposte comme s'il avait réussi une parade, s'étant déporté avec assez d'équilibre pour pouvoir placer un coup correct."
  },
  {
    "id": "melee-combattre-a-deux-armes",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Combattre à deux armes",
    "stats": {
      "difficulty": {
        "key": "selon",
        "note": "la main"
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "variables"
    },
    "inGameEffect": "Un dé d'Initiative supplémentaire (d'une autre couleur), modifié par l'arme secondaire : une action de plus, attaque ou parade avec la seconde arme uniquement, à -5 comme toute action supplémentaire. Ambidextre : cette action est gratuite.",
    "description": "Lorsqu'un protagoniste utilise une arme dans sa \"mauvaise main\", il lance un dé supplémentaire d'Initiative, d'une couleur différente de ses autres dés. Le chiffre obtenu est modifié selon l'arme secondaire. Ce dé est conservé en plus des dés normaux d'Initiative et donne droit à une action supplémentaire. Lors du décompte de l'Initiative, cette action est résolue comme les autres, mais utilise obligatoirement la seconde arme et ne peut donc compter que pour une attaque ou une parade. Toutes les actions effectuées avec cette arme secondaire subissent un malus de -5 comme toutes les actions supplémentaires (à moins bien sûr d'être la première attaque ou parade, auquel cas c'est l'arme principale qui subira le malus). Dans le cas d'un personnage ambidextre, l'action effectuée avec cette arme secondaire compte comme une action gratuite (elle subit les malus découlant d'actions précédentes mais n'en entraînera en revanche aucun).\nExemple : un personnage possède 3 en Initiative et utilise une épée courte et une dague. Il lance alors 4 dés, dont un de couleur différente. Il obtient 7, 5, 8 et 6 pour le dé différent. Ces résultats ne sont pas modifiés par ses armes. Il dispose donc de trois actions au maximum avec son épée courte à 7, 5 et 8 et d'une avec sa dague à 6. S'il agit dans l'ordre de ses actions, il pourra attaquer à 8 normalement, parer avec son 7 normalement (ou attaquer à -5), et agir avec sa dague à 6 (en parant à -5 ou en attaquant à -10), avant d'utiliser sa dernière action à 5. S'il avait été ambidextre, il aurait pu attaquer à 8 normalement, parer avec son 7 normalement (ou attaquer à -5), et agir avec sa dague à 6 (en parant cette fois normalement ou en attaquant à seulement -5), avant d'utiliser sa dernière action à 5."
  },
  {
    "id": "melee-desarmer",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Désarmer",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "impossible"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "aucun"
    },
    "roll": "Manuel + Compétence d'arme contre Manuel + Compétence d'arme",
    "inGameEffect": "Un NR de plus que l'adversaire le désarme ; égalité : rien. Récupérer l'arme coûte une action par NR. Les armes corporelles des créatures ne peuvent être ôtées. Échec critique : l'attaquant perd son arme, un tour complet pour la récupérer.",
    "description": "Une tentative de désarmement se résout par un jet d'opposition de Manuel + Compétence d'arme. Le personnage ayant obtenu un NR de plus que son adversaire le désarme (ce qui peut être à double tranchant). En cas d'égalité, les deux adversaires ferraillent sans résultats. Une arme ainsi ôtée atterrit non loin et il faut une action au défenseur par NR pour aller la récupérer. Certaines créatures intelligentes peuvent désarmer avec leurs armes corporelles (griffes de dragon, bec, etc.), mais ne peuvent pas être désarmées. Un échec critique fait perdre son arme à l'attaquant et il lui faut un tour complet pour la récupérer."
  },
  {
    "id": "melee-feinter",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Feinter",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "normale",
        "value": 15,
        "note": "inutile"
      },
      "parry": {
        "key": "normale",
        "value": 15,
        "note": "inutile"
      },
      "damage": "aucun"
    },
    "roll": "Manuel + Compétence d'arme contre Mental + Compétence d'arme",
    "inGameEffect": "Avec un NR, le défenseur doit dépenser une action pour se défendre. L'attaquant porte alors une attaque gratuite de son choix ; s'en défendre coûte +5 à la Difficulté (action supplémentaire de défense).",
    "description": "La feinte consiste à obliger le défenseur à parer ou à esquiver, en lui faisant croire qu'une attaque meurtrière est portée contre lui. Une feinte se résout par un jet d'opposition de Manuel + Compétence d'arme contre Mental + Compétence d'arme du défenseur. Si l'attaquant obtient un NR, l'attaque est comme réelle et le défenseur doit dépenser une action pour se défendre car il se croira menacé. Sinon, la ruse est éventée.\nSi la feinte fonctionne, l'attaquant peut immédiatement porter une attaque gratuite de son choix. Cette attaque ne coûte pas d'action (c'est la feinte qui l'utilise). Elle subit les malus d'éventuelles attaques préliminaires dans le tour mais n'en entraînera aucun. Si le défenseur tente de parer ou d'esquiver cette deuxième attaque, qui est en fait la vraie, la Difficulté de son jet de défense sera augmentée de 5, car il s'agira d'une action supplémentaire de défense."
  },
  {
    "id": "melee-maintenir-a-distance",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Maintenir à distance",
    "stats": {
      "difficulty": {
        "key": "special"
      },
      "dodge": {
        "key": "non-applicable"
      },
      "parry": {
        "key": "non-applicable"
      },
      "damage": "aucun"
    },
    "inGameEffect": "Arme d'hast uniquement. L'adversaire doit d'abord déborder : son attaque est « parée » par Manuel + Compétence d'arme + bonus de maintien à distance. Revenir à distance coûte une action. Les armes d'hast gardent leur modificateur d'Initiative tant que l'adversaire est maintenu, sinon 0.",
    "description": "Cette manœuvre n'est possible qu'avec une arme d'hast. Un adversaire maintenu à distance ne peut attaquer le défenseur avant de l'avoir débordé. Pour cela, il doit réussir à porter une attaque que le porteur de l'arme d'hast devra \"parer\" en interposant son arme par un jet de Manuel + Compétence d'arme, augmenté de son bonus de maintien à distance. Si l'attaquant parvient à déborder, il entre en mêlée contre le défenseur, qui doit alors se battre normalement. Ce dernier peut se remettre à distance de maintien en dépensant une action pour se déplacer. Pour le suivre et rester en mêlée, l'attaquant devra faire de même. Les armes d'hast bénéficient de leur modificateur d'Initiative tant que l'adversaire est maintenu à distance, sans quoi il devient de 0."
  },
  {
    "id": "melee-entrer-au-corps-a-corps",
    "contexte": "melee",
    "famille": "manoeuvre",
    "nom": "Entrer au corps à corps",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "opposition"
      },
      "parry": {
        "key": "opposition"
      },
      "damage": "aucun"
    },
    "roll": "Physique + Corps à corps contre Physique + Compétence d'arme (ou Physique + Esquive)",
    "inGameEffect": "Un NR pour l'attaquant : les deux passent au corps à corps. Échec critique : l'attaquant se blesse sur l'arme interposée (dommages de base, sans dé) ou trébuche au sol.",
    "description": "Entrer au corps à corps consiste à se rapprocher suffisamment de son adversaire pour pouvoir utiliser des armes courtes, les poings ou les pieds. Passer au corps à corps permet d'utiliser les manœuvres de corps à corps (voir paragraphe suivant) et de gêner l'usage des armes longues ou encombrantes. Passer en corps à corps nécessite un jet d'opposition de Physique + Corps à corps de l'attaquant contre Physique + Compétence d'arme (si le défenseur interpose son arme) ou Physique + Esquive s'il recule et contourne l'attaquant. Si ce jet obtient un NR en faveur de l'attaquant, les deux adversaires passent au corps à corps. S'il est manqué ou égal, rien ne se passe. Si c'est un échec critique, l'attaquant trébuche et se blesse sur l'arme que le défenseur interpose (si le jet était en Physique + Compétence d'arme) ou trébuche au sol (si le jet était en Physique + Esquive). En cas de blessure accidentelle, les dommages subis sont les dommages de base de l'arme sans qu'aucun dé ne soit jeté."
  },
  {
    "id": "cac-attaque-simple",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Attaque simple",
    "stats": {
      "difficulty": {
        "value": 15
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "normaux"
    },
    "inGameEffect": "Aucun effet particulier.",
    "description": "L'attaquant porte un coup classique avec pour objectif de toucher son adversaire."
  },
  {
    "id": "cac-assommer",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Assommer",
    "stats": {
      "difficulty": {
        "value": 20
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "normale",
        "value": 15
      },
      "damage": "aucun"
    },
    "inGameEffect": "Comme en mêlée. À mains nues, impossible contre un casque avec armure moyenne ou lourde, ou contre un heaume solide.",
    "description": "Assommer dans un combat au corps à corps est une manœuvre identique à la celle à effectuer en mêlée. Toutefois, si l'attaquant porte un coup à mains nues, il ne peut pas tenter d'assommer un adversaire portant un casque avec une armure moyenne ou lourde (ou s'il porte un heaume solide quelle que soit son armure, et que ce dernier a été avalisé par le meneur de jeu)."
  },
  {
    "id": "cac-incapaciter",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Incapaciter",
    "stats": {
      "difficulty": {
        "value": 25
      },
      "dodge": {
        "key": "normale",
        "value": 15
      },
      "parry": {
        "key": "difficile",
        "value": 20
      },
      "damage": "spéciaux"
    },
    "inGameEffect": "Au moins une blessure légère : le défenseur est incapacité un nombre de tours égal aux NR de l'attaque ; il ne peut que se défendre, à Difficulté +10, et aucune action offensive.",
    "description": "Ce type d'attaque est particulièrement vicieux, puisqu'il permet de mettre son adversaire hors d'état de combattre en le frappant au bas-ventre, aux yeux, aux oreilles, aux doigts de la main d'arme, etc. La Difficulté de l'attaque est augmentée car il faut impérativement viser une zone \"vitale\". S'il subit au moins une blessure légère, le défenseur est incapacité pendant un nombre de tours égal aux NR de l'attaque. Durant cette douloureuse période, il ne peut que se défendre avec une Difficulté augmentée de 10 et ne peut tenter la moindre action offensive."
  },
  {
    "id": "cac-renverser",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Renverser",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "opposition"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "aucun"
    },
    "roll": "Physique + Corps à corps contre Physique + Esquive (ou Acrobatie)",
    "inGameEffect": "Un NR : l'adversaire tombe et combat au sol. Échec critique : c'est l'attaquant qui tombe.",
    "description": "Une tentative de renversement se résout par un jet d'opposition de Physique + Corps à corps contre Physique + Esquive (ou Acrobatie). Si l'attaquant obtient un NR, il fait tomber son adversaire qui doit alors combattre au sol. En cas d'échec critique, c'est lui qui se retrouve au sol."
  },
  {
    "id": "cac-ecraser",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Écraser",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "opposition",
        "note": "si possible"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "variables"
    },
    "roll": "Physique + Athlétisme contre Physique + Esquive",
    "inGameEffect": "Dommages : Force × 2 + pénalité d'encombrement d'armure (en positif), + dommages de chute si l'attaquant tombe d'une hauteur. Échec : l'attaquant subit ces dommages ; échec critique : il est aussi assommé 2D10 tours. La victime est au sol, l'attaquant sur elle : se relever demande Physique + Coordination contre son Indice de protection, malus = Physique de l'attaquant + son malus d'encombrement.",
    "description": "Plonger sur son adversaire de tout son poids est une bonne façon de l'incapaciter. Cette situation peut se produire lorsqu'un adversaire vient d'être jeté au sol ou lorsque l'attaquant surprend sa victime (en sautant d'un toit par exemple).\nPlonger sur un adversaire se résout par un jet d'opposition de Physique + Athlétisme contre Physique + Esquive (si ce dernier est averti de l'attaque). Si ce dernier est un échec, la chute se fait à côté de la cible et l'attaquant subit les dommages qu'aurait dû subir la victime. S'il s'agit d'un échec critique, l'attaquant s'assomme automatiquement pour 2D10 tours en plus des dommages. Ces dommages varient selon que le personnage tombe de sa hauteur ou d'une éminence.\nS'il tombe de sa hauteur, il inflige (Force x 2) dommages, plus la valeur positive de sa pénalité d'encombrement d'armure.\nS'il tombe d'une hauteur, il inflige (Force x 2) dommages, plus la valeur positive de sa pénalité d'encombrement d'armure et les dommages de chute qu'il aurait dû subir.\nUn adversaire écrasé est systématiquement jeté au sol avec le personnage sur lui.\nPour se relever, le combattant doit réussir un jet de Physique + Coordination contre une Difficulté égale à son Indice de protection, en subissant un malus égal au Physique de celui qui l'écrase plus le malus d'encombrement de l'armure de ce dernier."
  },
  {
    "id": "cac-saisir",
    "contexte": "corps-a-corps",
    "famille": "manoeuvre",
    "nom": "Saisir",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "opposition"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "aucun"
    },
    "roll": "Physique + Corps à corps contre Physique + Esquive",
    "inGameEffect": "Chaque NR de l'attaquant : +1 à sa prochaine action. Ouvre les manœuvres d'empoignade. La victime saisie n'utilise plus que des armes de corps à corps, attaque simple, incapaciter, saisir ou renversement. Se dégager : une action, Physique + Corps à corps en opposition.",
    "description": "Saisir son adversaire se résout par un jet d'opposition de Physique + Corps à Corps contre Physique + Esquive. Tous les NR obtenus par l'attaquant seront comptés comme des bonus de +1 par NR pour sa prochaine action. Les NR du défenseur sont gérés de façon classique selon qu'il utilise une arme pour \"parer\" ou qu'il esquive. Une fois un adversaire saisi, l'attaquant peut alors tenter l'une des trois manœuvres d'empoignade décrites page 188. Tant que ce dernier ne sera pas dégagé, que l'attaquant n'aura pas mis fin à sa prise ou effectué une manœuvre débouchant sur une libération, la victime ne peut plus utiliser d'armes autres que les armes de corps à corps ou les manœuvres d'attaque simple, incapaciter, saisir ou renversement.\nSe dégager d'une prise oblige le défenseur à effectuer un jet d'opposition de Physique + Corps à corps contre Physique + Corps à corps de son adversaire. Cette tentative consomme une action."
  },
  {
    "id": "cac-manoeuvres-d-empoignade",
    "contexte": "corps-a-corps",
    "famille": "empoignade",
    "nom": "Manœuvres d'empoignade",
    "inGameEffect": "Accessibles seulement après avoir saisi l'adversaire.",
    "description": "Ces manœuvres ne sont accessibles que si l'attaquant a saisi son adversaire."
  },
  {
    "id": "cac-etrangler",
    "contexte": "corps-a-corps",
    "famille": "empoignade",
    "nom": "Étrangler",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "opposition"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "spéciaux"
    },
    "roll": "Manuel + Corps à corps contre Manuel + Esquive",
    "inGameEffect": "Victime privée d'air : tient autant d'actions que sa Résistance, puis coche une case de blessure par action (égratignures d'abord). Chaque début de tour, Résistance + Volonté contre 5, 10, 15… pour rester consciente ; inconsciente, elle meurt si on ne la relâche pas.",
    "description": "L'attaquant tente de déplacer sa prise sur la gorge de son adversaire pour le faire suffoquer. Ce déplacement se résout par un jet d'opposition de Manuel + Corps à corps contre Manuel + Esquive du défenseur. Si l'attaquant réussit à déplacer sa prise, la victime est privée d'air. Contrairement aux règles de suffocation présentées page 194, l'asphyxie sous la pression du combat survient beaucoup plus vite. Un personnage peut supporter le manque d'air durant autant d'actions que sa Résistance. Au début de chaque action supplémentaire, il coche une case de blessure, en commençant par les égratignures. Pour rester conscient, il doit réussir à chaque début de tour un jet de Résistance + Volonté contre 5 au premier tour, puis 10 au deuxième tour, 15 au troisième et ainsi de suite. S'il sombre dans l'inconscience, il ne peut plus agir et décèdera à coup sûr à moins que son adversaire ne le relâche..."
  },
  {
    "id": "cac-immobiliser",
    "contexte": "corps-a-corps",
    "famille": "empoignade",
    "nom": "Immobiliser",
    "stats": {
      "difficulty": {
        "key": "opposition"
      },
      "dodge": {
        "key": "special"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "aucun"
    },
    "roll": "Physique + Corps à corps contre Physique + Coordination",
    "inGameEffect": "Un NR : clé bloquée, la victime ne peut que tenter de se libérer ou se rendre. Se libérer : Physique + Corps à corps contre 25, chaque échec -2 à la tentative suivante.",
    "description": "L'attaquant tente de transformer sa prise en clé. Il doit effectuer un jet d'opposition de Physique + Corps à corps contre Physique + Coordination de son adversaire. S'il obtient un NR, il bloque sa clé. Un adversaire immobilisé ne peut plus effectuer d'autres actions que de tenter de se libérer ou se rendre.\nSe libérer d'une clé nécessite un jet de Physique + Corps à corps contre une Difficulté de 25. Tout échec entraîne un malus de -2 sur la prochaine tentative."
  },
  {
    "id": "cac-projeter",
    "contexte": "corps-a-corps",
    "famille": "empoignade",
    "nom": "Projeter",
    "stats": {
      "difficulty": {
        "value": 15
      },
      "dodge": {
        "key": "impossible"
      },
      "parry": {
        "key": "impossible"
      },
      "damage": "possibles"
    },
    "roll": "Physique + Corps à corps",
    "inGameEffect": "Dommages 1D10 + NR. La victime peut tenter une manœuvre de corps à corps à +5 (un dégagement réussi : chute sans dommages) ou préparer sa chute : Physique + Acrobatie contre 15, ses NR retranchés de ceux de l'attaquant.",
    "description": "Un personnage saisi peut être projeté par l'attaquant. Cette projection s'effectue par un jet de Physique + Corps à corps contre une Difficulté de 15. La projection provoque (1D10 + NR) points de dommages. Un personnage qui va être projeté sent la manœuvre venir. Il peut alors au choix soit tenter une manœuvre de corps à corps avec un bonus de +5 ou bien préparer sa réception pour amortir le choc. Si l'action entreprise (et réussie) est un dégagement, la prise est brisée et la victime tombe au sol en se libérant, mais sans dommages. S'il décide de préparer sa chute, il pourra effectuer un jet de Physique + Acrobatie contre une Difficulté 15, dont les NR éventuels seront soustraits aux NR de l'attaquant pour le calcul des dommages."
  },
  {
    "id": "cac-combat-au-corps-a-corps",
    "contexte": "corps-a-corps",
    "famille": "regle",
    "nom": "Le combat au corps à corps",
    "inGameEffect": "Les modificateurs d'Initiative des armes diffèrent en mêlée et au corps à corps (tableau des armes). Une parade armée contre des coups à mains nues se résout comme en mêlée.",
    "description": "Le combat au corps à corps permet toutes sortes de coups spéciaux, tels que les projections, les étranglements ou les immobilisations en plus des attaques à mains nues plus simples comme les coups de poing ou de pied.\nLe corps à corps peut se pratiquer avec des armes, utilisant alors des armes de petite taille (poignard, gants à pointes, etc.). Il diffère beaucoup du combat de mêlée, en raison de la proximité des combattants. Les armes dans le corps à corps sont gérées un peu différemment que dans une mêlée. Ainsi, les modificateurs d'Initiative des armes sont différents selon qu'on les utilise en mêlée ou au corps à corps. Le tableau des armes (cf. pages 149 à 151) présente ces différences et permet de se rendre compte qu'une arme longue et capable de frapper avec une bonne allonge peut vite devenir un handicap si l'adversaire vous colle de trop près. La parade armée contre les coups à mains nues est résolue de la même façon qu'en mêlée. On considère seulement que le défenseur interpose son arme et que l'attaquant interrompt lui-même son coup pour éviter de se blesser. En cas d'échec critique en attaque, le meneur de jeu pourra s'inspirer de la manœuvre entrer au corps à corps pour gérer d'éventuelles blessures."
  },
  {
    "id": "cac-dommages-des-coups",
    "contexte": "corps-a-corps",
    "famille": "regle",
    "nom": "Dommages des coups",
    "inGameEffect": "Coups de pied ou de poing : blessures cochées normalement, mais une blessure mortelle rend inconscient ; l'adversaire doit déclarer qu'il achève pour tuer.",
    "description": "Les dommages infligés par des armes de corps à corps sont notés dans la liste d'équipement et se gèrent comme dans le cadre d'un combat armé. Par contre, les dommages infligés par de simples coups de pied ou de poing ne sont pas considérés comme des blessures mortelles, bien qu'ils soient gérés normalement par les cases de blessure. Lorsqu'un personnage subit une blessure mortelle du fait d'un coup à mains nues, il sombre dans l'inconscience. Pour qu'il décède, son adversaire doit spécifier au meneur de jeu qu'il l'achève et provoque la mort. Les modificateurs liés aux blessures s'appliquent normalement, que les blessures soient provoquées par une arme ou à mains nues. Toutefois, le temps de récupération des blessures à mains nues est différent de celui des autres."
  },
  {
    "id": "cac-combat-au-sol",
    "contexte": "corps-a-corps",
    "famille": "regle",
    "nom": "Le combat au sol",
    "inGameEffect": "Au sol : actions offensives +10 en Difficulté, défensives +5. Se relever : Physique + Coordination contre l'Indice de protection, sans pénalité d'encombrement d'armure.",
    "description": "Un combattant au sol est dans une situation très dangereuse. Toutes ses actions offensives subissent une augmentation de Difficulté de +10 et ses actions défensives de +5.\nPour se relever, le combattant doit réussir un jet de Physique + Coordination contre une Difficulté égale à son Indice de protection. Dans ce cas, il ne prend pas en compte sa pénalité d'encombrement d'armure."
  },
  {
    "id": "monte-charger",
    "contexte": "monte",
    "famille": "manoeuvre",
    "nom": "Charger",
    "roll": "Physique + Équitation (Difficulté 15)",
    "inGameEffect": "Chaque NR : +1 à l'attaque, résolue comme une charge en mêlée avec la Force de la monture aux dommages. Toujours deux actions d'élan ; renversement automatique.",
    "description": "Un cavalier qui souhaite attaquer en charge doit effectuer un jet de Physique + Équitation contre une Difficulté de 15. Pour chaque NR, il gagne un bonus de 1 sur son jet d'attaque et applique alors une attaque de charge comme en mêlée, mais en ajoutant la Force de sa monture au lieu de la sienne aux dommages. Une charge d'une monture est toujours considérée comme ayant deux actions d'élan. Une attaque de renversement est automatiquement appliquée du fait du choc, même si la monture ne percutera pas volontairement le fantassin visé."
  },
  {
    "id": "monte-receptionner-une-charge",
    "contexte": "monte",
    "famille": "manoeuvre",
    "nom": "Réceptionner une charge",
    "roll": "Physique + Compétence d'arme (Difficulté 15)",
    "inGameEffect": "+10 à la Difficulté sans arme de contre-charge. Réussite sans NR : le coup porte mais le fantassin subit la charge ; avec un NR, il se dégage. L'arme est perdue dans tous les cas. Dommages doublés.",
    "description": "Un fantassin qui souhaite réceptionner une charge doit soit viser le cheval, soit viser le cavalier. Dans les deux cas, il faut effectuer un jet de Physique + Compétence d'arme contre une Difficulté de 15. Cette Difficulté est augmentée de 10 si l'arme utilisée n'est pas une arme dotée de la capacité de contre-charge (cf. tableau des armes, pages 149 à 151). Si le jet est réussi sans NR, le coup porte mais le fantassin subit tout de même les effets de la charge. Avec un NR ou plus, le fantassin se dégage de justesse. Dans les deux cas, un fantassin qui effectue une contre-charge perd son arme dans la manœuvre, car elle est soit brisée, soit sous la monture affaissée ou bien bloquée dans le corps de cette dernière. Les dommages d'une réception de charge sont doublés (cf. tableau des armes, pages 149 à 151)."
  },
  {
    "id": "monte-desarconner",
    "contexte": "monte",
    "famille": "manoeuvre",
    "nom": "Désarçonner",
    "roll": "Physique + Compétence d'arme (Difficulté 20)",
    "inGameEffect": "Chaque NR : +5 à l'esquive du cavalier (15 de base). Réussite simple : Difficultés +5 pour le tour ; un NR : il reste en selle. Esquive manquée : dommages de l'arme + 2D10 de chute (3D10 en armure moyenne ou lourde), sans Indice de protection.",
    "description": "Pour désarçonner un cavalier fermement campé en selle, il faut effectuer un coup visé de Physique + Compétence d'arme contre une Difficulté de 20. Chaque NR augmente de 5 la Difficulté du jet d'esquive du cavalier (15 de base). S'il obtient une réussite simple, le cavalier est tout de même déséquilibré et la Difficulté de tous ses jets pour le restant du tour est augmentée de 5. S'il obtient au moins un NR, il n'est pas touché et reste en selle sans problèmes. S'il manque son esquive, il est violemment percuté et vide ses étriers. Il subit alors les dommages de l'arme ayant été utilisée (avec d'éventuels modificateurs de charge ou autre et en comptant l'armure). De plus, il subit 2D10 de dommages (3D10 s'il porte une armure moyenne ou lourde) du fait de la chute et ce sans appliquer l'Indice de protection de l'armure."
  },
  {
    "id": "monte-montures-dans-les-combats",
    "contexte": "monte",
    "famille": "regle",
    "nom": "Les montures dans les combats",
    "description": "Lorsque tous les protagonistes d'un combat sont à pied ou à cheval, les règles sont simples. Dans la gestion d'un combat opposant des cavaliers à des fantassins, les notions de charge et de réception de charge sont très importantes, tout comme les manœuvres que les deux combattants seront obligées d'effectuer pour attaquer ou esquiver un coup, et ce en raison de la différence de mobilité et d'allonge dont les deux adversaires disposent."
  },
  {
    "id": "monte-actions-en-selle",
    "contexte": "monte",
    "famille": "regle",
    "nom": "Actions offensives et défensives en selle",
    "inGameEffect": "Esquive en selle : Physique + Équitation au lieu de Physique + Esquive. Chaque début de tour : Physique + Équitation contre 15 (20 monture jamais au feu, 25 à peine débourrée) ou perdre une action à la calmer.",
    "description": "Toutes les esquives d'un cavalier en selle sont résolues par un jet de Physique + Équitation, au lieu de Physique + Esquive.\nAu début de chaque tour, un cavalier qui combat doit effectuer un jet de Physique + Équitation contre 15 pour tenir sa monture ou perdre une action qui sert alors automatiquement à la calmer et à la diriger. Le meneur de jeu pourra à son gré redemander un jet d'Équitation ou pourra décider que le cavalier réussit sans jet du moment qu'il prend le temps.\nLa Difficulté de ce jet pourra atteindre 20 pour une monture n'ayant jamais été au feu et même 25 pour une monture à peine débourrée et pas encore dressée."
  },
  {
    "id": "situations-particulieres",
    "contexte": "situations",
    "famille": "regle",
    "nom": "Situations particulières",
    "description": "Tous les combats de Prophecy ne se dérouleront pas dans des conditions faciles et, à très court terme, le meneur de jeu risque de devoir gérer des situations aussi délicates que des combats dans l'eau, en équilibre ou en infériorité numérique. Toutes les actions décrites précédemment restent possibles quel que soit le contexte de l'affrontement, mais chaque situation devra être représentée en termes d'une Difficulté ajustée de bonus/malus."
  },
  {
    "id": "situations-environnement-de-combat",
    "contexte": "situations",
    "famille": "regle",
    "nom": "L'environnement de combat",
    "inGameEffect": "Pont instable -2 ; corniche étroite Difficultés +5 ; eau aux genoux -3 ; eau à la taille Difficultés +5 ; sol spongieux, glissant, neige ou boue -4 ; sol mouillé -2 ; tempête Difficultés +5 ; très forte chaleur : la pénalité d'encombrement d'armure s'applique aux Compétences de Combat.",
    "description": "Le climat, la nature du sol et l'équilibre sont autant de paramètres fondamentaux lors d'un combat. Si le pont se met à tanguer, que la tempête se déchaîne ou que la chaleur monte, il y a fort à parier que la Difficulté des jets augmentera en même temps que la tension des combattants...\nLe personnage combat...\n• sur un pont instable : -2 aux jets\n• sur une corniche étroite : Difficultés +5, impossibilité d'effectuer certaines actions\n• dans l'eau jusqu'aux genoux : -3 aux jets, pas de sprint possible\n• dans l'eau jusqu'à la taille : Difficultés +5, pas de course possible\n• sur un sol spongieux ou glissant, dans la neige ou la boue : -4 aux jets, pas de course possible (jets d'Acrobatie possibles)\n• sur sol mouillé : -2 aux jets\n• dans une tempête : Difficultés +5\n• par une très forte chaleur : la pénalité d'encombrement de l'armure s'applique aussi aux Compétences de Combat."
  },
  {
    "id": "critiques-coups-critiques",
    "contexte": "critiques",
    "famille": "regle",
    "nom": "Coups critiques",
    "inGameEffect": "Réussite critique au toucher : lancer un D10 sur une table de critiques. Dé unique : table générale. Avec les Tendances : table de la Tendance dont le dé a été conservé (Homme, Dragon, Fatalité), en ajoutant son niveau dans cette Tendance au D10.",
    "description": "Lorsqu'une réussite critique est obtenue sur un jet de toucher, le joueur doit lancer un D10 pour déterminer les effets exacts de son coup. Plus le résultat de ce jet sera élevé, plus le coup critique sera dévastateur. Pour calculer les dommages infligés par l'attaque, il faut reporter le résultat du dé sur l'une des quatre tables de critiques existantes.\nSi le coup critique a été obtenu grâce à un dé unique, il faut se reporter à la table générale. Si le joueur avait fait appel aux Tendances pour résoudre son jet d'attaque, il devra se reporter à la table correspondant à la Tendance dont il a conservé le dé : celle de l'Homme, celle du Dragon ou celle de la Fatalité. Chaque table possède son propre style. Alors que les effets de la table générale sont assez conventionnels (blessures graves, coups puissants, etc.) et donnent juste un bonus aux dommages, ceux des trois tables de Tendance sont nettement plus \"engagés\". Les critiques du Dragon interprètent les dommages de façon héroïque, en proposant des coups spectaculaires et des effets spéciaux typiquement draconiques. Ceux de l'Homme sont plus subtils, fondés sur la ruse et l'aspect technique du combat. Enfin, les coups critiques de la Fatalité sont à l'image de Kalimsshar : horribles, impitoyables et destructeurs.\nLorsqu'un joueur obtient une réussite critique grâce à un dé d'une Tendance, il ajoute son niveau dans cette Tendance au dé qu'il lance pour déterminer les effets du coup critique. Ainsi, un personnage possédant une Tendance élevée pourra facilement dépasser 10 sur ce jet et viser les effets les plus dévastateurs de la table correspondante."
  }
];
