// GENERATED by scripts/build-catalogs.ts from data-src/privileges.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { PrivilegePreset } from './privilege-catalog';

export const PRIVILEGE_CATALOG_DATA: PrivilegePreset[] = [
  {
    "id": "artisan-apprenti",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Apprenti",
    "cout": 3,
    "description": "Permet de disposer d'un apprenti artisan qui, en plus de rendre de menus services au personnage, pourra s'occuper de son atelier en son absence, porter des messages, colporter des rumeurs et effectuer certaines tâches de base. L'apprenti doit être instruit et demandera un peu de temps et d'attention de la part de son maître. Au bout de quelques années, l'apprenti quittera le personnage pour se lancer seul."
  },
  {
    "id": "artisan-autorisation",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Autorisation",
    "cout": 4,
    "description": "Permet de pratiquer la mécanique pour réaliser des objets ou des machines d'intérêt public (engins de levage, horloges, roues de moulins, etc.). Ce Privilège ne permet pas de connaître la Compétence Mécanique (qui doit être apprise avec l'Avantage Art interdit) mais simplement de la pratiquer de façon relativement libre. Le personnage dispose d'un sceau conféré par les maîtres de sa caste qui lui servira à marquer visiblement l'objet. Tous ses travaux dépendant de cette autorisation seront toujours validés par une commande transmise par la caste et validée par l'Inquisition."
  },
  {
    "id": "artisan-charte-d-atelier",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Charte d'atelier",
    "cout": 4,
    "description": "Permet de disposer d'une autorisation d'accès aux ateliers des artisans résidents. Elle se présente sous la forme d'une série de broderies apposées sur son tablier de sortie. Elles lui garantissent un accueil favorable chez ses confrères, qui lui demanderont alors un dédommagement plus modique pour prêter un établi et quelques outils. Ce Privilège permet évidemment d'éviter les hausses de Difficulté dues à un matériel insuffisant. De plus, le personnage ne subira pas les allongements de délai de création dus au travail solitaire."
  },
  {
    "id": "artisan-familier",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Familier",
    "cout": 1,
    "description": "Permet de posséder un petit animal intelligent, généralement un oiseau ou un mammifère, capable d'échanger des émotions et des informations sommaires avec le personnage et de lui rendre quelques menus services (porter un outil, maintenir deux pièces ensemble, etc.)."
  },
  {
    "id": "artisan-notable",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Notable",
    "cout": 3,
    "description": "Permet de disposer d'une réputation et d'une clientèle de choix, de pouvoir compter sur l'aide de dignitaires locaux et d'être bien vu par un grand nombre de personnalités importantes de la ville et de ses environs."
  },
  {
    "id": "artisan-outils",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Outils",
    "cout": 4,
    "description": "Permet au personnage de disposer d'outils particulièrement efficaces et utilisés depuis longtemps, qui lui confèrent un bonus de 2 à toutes les actions en rapport avec son métier. Il appartient au meneur de jeu de restreindre les applications de ces outils, qui doivent logiquement être utilisables par un membre de la caste des artisans. Ils seront donc prioritairement utilisables avec des Compétences d'artisanat ou, plus largement, manuelles."
  },
  {
    "id": "artisan-psychometrie",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Psychométrie",
    "cout": 5,
    "description": "Permet, rien qu'en touchant un objet, d'en découvrir automatiquement la fonction, l'âge, l'origine géographique et le sexe du dernier propriétaire en date. En réussissant un jet de Manuel + Empathie contre une Difficulté de 10, le personnage peut obtenir, pour chaque NR, une réponse à une question supplémentaire concernant l'objet (nature magique de l'objet, dernière utilisation, etc.)."
  },
  {
    "id": "artisan-reparation-de-routine",
    "caste": "artisan",
    "famille": "caste",
    "nom": "Réparation de routine",
    "cout": 4,
    "description": "Permet d'improviser une réparation de fortune pour les objets courants. Le personnage est habitué à utiliser les moyens du bord et s'en sortira même s'il lui manque certains matériaux. En effectuant un jet de Manuel + Coordination, il improvise une solution qui durera 1 + NR jours. Toute réparation de routine sur un objet en ayant déjà bénéficié se verra infliger un malus cumulatif de 5."
  },
  {
    "id": "artisan-expertise",
    "caste": "artisan",
    "famille": "annexe",
    "nom": "Expertise",
    "cout": 4,
    "description": "Permet de confirmer ou d'infirmer l'authenticité de n'importe quel objet."
  },
  {
    "id": "artisan-faveur-politique",
    "caste": "artisan",
    "famille": "annexe",
    "nom": "Faveur politique",
    "cout": 4,
    "description": "Permet d'avoir tissé un réseau de relations politiques dans les principales villes d'un royaume. Ce réseau s'appuie sur des amitiés, des pots de vin et des services mutuels. Le personnage pourra obtenir plus facilement certaines informations (dates, projets de lois, ragots, etc.). Ce Privilège peut être choisi plusieurs fois et s'applique à un pays à chaque fois."
  },
  {
    "id": "artisan-tuteur",
    "caste": "artisan",
    "famille": "annexe",
    "nom": "Tuteur",
    "cout": 8,
    "description": "Permet de bénéficier de l'aide et de la bienveillance d'un mage de Statut égal au sien, que l'artisan a connu lors de son intéressement à la sorcellerie au sein d'une académie. Si ce mage n'est pas censé intervenir directement lors des aventures, il peut prodiguer des conseils, des enseignements ou lancer pour le personnage quelques sorts mineurs — en échange de petits services."
  },
  {
    "id": "combattant-adaptation",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Adaptation",
    "cout": 3,
    "description": "Permet d'improviser une technique de combat avec des armes de fortune (chaises, bâtons, pierres) ou des armes dont il ne possède pas la Compétence. Il faut pour cela réussir un jet de Mental + Coordination + niveau de Statut contre une Difficulté de 5 (si l'arme est relativement simple d'usage) ou de 10 (si elle est incongrue ou délicate à manier). Pour la durée du combat, le personnage gagne un niveau de Compétence égal à 1 + nombre de NR. Il est nécessaire d'effectuer un jet pour chaque type d'arme et pour chaque combat."
  },
  {
    "id": "combattant-argot-combattant",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Argot combattant",
    "cout": 2,
    "description": "Permet de manier un langage basé sur les signes, le mouvement des yeux et les postures, afin de communiquer silencieusement des informations. Il n'y a aucun jet à effectuer, mais les informations doivent être simples (couvre-moi, attention sur le flanc, j'en vois deux, etc.) et l'interlocuteur du personnage doit obligatoirement posséder ce Privilège pour le comprendre."
  },
  {
    "id": "combattant-botte-secrete",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Botte secrète",
    "cout": 5,
    "description": "Permet de maîtriser un coup vicieux et imprévisible qui déroutera sensiblement son adversaire. Le joueur doit préciser la nature de ce coup : coup visé, attaque précise, charge, etc. Il peut s'agir d'un coup existant (voir Système de jeu) ou d'un coup rare apprécié par le personnage. Lorsqu'il utilise ce coup, les jets de parade ou d'esquive de l'adversaire voient leur Difficulté augmenter de 5. Ce dernier peut cependant effectuer un jet de Mental + Compétence d'arme concernée contre une Difficulté de 20 pour comprendre la manœuvre et annuler la Difficulté supplémentaire. La Difficulté de ce jet est réduite de 5 à chaque nouveau jet."
  },
  {
    "id": "combattant-double-attaque",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Double attaque",
    "cout": 6,
    "description": "Permet d'effectuer, une fois par tour de combat, une deuxième attaque lors d'un même rang d'action et ce, sans subir de Difficulté supplémentaire. La première attaque s'effectue normalement, mais la seconde voit ses dommages amputés d'un dé. Aucune manœuvre n'est possible sur cette nouvelle attaque."
  },
  {
    "id": "combattant-engagement",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Engagement",
    "cout": 4,
    "description": "Permet d'ignorer, une fois par combat et pendant un tour complet, tous les malus découlant de ses blessures. Les malus reviennent normalement au début du tour suivant."
  },
  {
    "id": "combattant-feinte",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Feinte",
    "cout": 6,
    "description": "Permet de porter un coup simulé que l'adversaire tentera de parer ou d'esquiver. Cette technique, particulièrement efficace, a pour effet principal d'augmenter la Difficulté des jets suivants de l'adversaire car, si la feinte ne compte pas comme une action, la parade et/ou l'esquive le sont bel et bien. Le personnage peut donc feindre une attaque, contraindre à la défense et porter une véritable attaque sans aucun malus. Une seule feinte est possible lors d'un même tour. Après la première feinte, l'adversaire a droit à un jet de Mental + Compétence d'arme concernée contre une Difficulté de 15 pour comprendre qu'il ne s'agit pas d'une véritable attaque. La Difficulté de ce jet est réduite de 5 à chaque nouvelle feinte. Un personnage disposant de ce Privilège sur le point de subir une feinte peut directement effectuer le jet de Mental + Compétence d'arme concernée pour deviner la feinte (il n'est pas obligé d'attendre APRÈS l'avoir subie une fois). La Difficulté reste inchangée."
  },
  {
    "id": "combattant-riposte",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Riposte",
    "cout": 5,
    "description": "Permet d'effectuer une contre-attaque immédiatement après avoir paré ou esquivé un coup et ce, quel que soit le nombre de NR. Il est impossible d'effectuer une manœuvre. La Difficulté reste inchangée, mais les dommages sont réduits d'un dé. Une seule riposte est possible par tour."
  },
  {
    "id": "combattant-vigilance",
    "caste": "combattant",
    "famille": "caste",
    "nom": "Vigilance",
    "cout": 4,
    "description": "Permet de deviner le comportement de son adversaire au début d'un tour de combat. Il faut pour cela réussir un jet de Mental + Compétence de l'arme utilisée par l'adversaire contre une Difficulté de 15. Si l'adversaire ne compte pas attaquer, sa Compétence d'arme est remplacée par la Caractéristique qu'il va utiliser (Coordination s'il s'agit d'une fuite ou d'un mouvement, par exemple). Le personnage gagne un bonus égal au nombre de NR sur une parade, une esquive ou le rang de l'un de ses dés d'Initiative. Il est possible d'attaquer avant l'adversaire si l'Initiative du personnage devient supérieure grâce à ce bonus."
  },
  {
    "id": "combattant-allies-mercenaires",
    "caste": "combattant",
    "famille": "annexe",
    "nom": "Alliés mercenaires",
    "cout": 6,
    "description": "Permet de disposer d'un réseau d'anciens compagnons d'armes capables de lui apporter une aide non négligeable. Ce Privilège peut permettre d'obtenir des informations, de demander un soutien actif ou de disposer d'un petit nombre d'hommes de main en peu de temps. Il n'est applicable qu'au sein d'une cité comptant des groupes de mercenaires respectueux des enseignements de Kroryn."
  },
  {
    "id": "combattant-compagnons-de-bataille",
    "caste": "combattant",
    "famille": "annexe",
    "nom": "Compagnons de bataille",
    "cout": 6,
    "description": "Permet de disposer d'un vieux compagnon de campagnes dans n'importe quelle cité comptant plus de cinq mille habitants. Cet ami pourra rendre des services, fournir des renseignements ou apporter une aide variée — hébergement, prêt de matériel, etc."
  },
  {
    "id": "combattant-maitrise-d-armure",
    "caste": "combattant",
    "famille": "annexe",
    "nom": "Maîtrise d'armure",
    "cout": 10,
    "description": "Permet de rendre son armure particulièrement résistante à un type d'attaque précis. Pour utiliser ce Privilège, le personnage doit obligatoirement être spécialisé dans l'arme contre laquelle il souhaite renforcer son armure. L'Indice de protection augmente de 10 face à ce type d'attaque."
  },
  {
    "id": "commercant-bonne-fortune",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Bonne fortune",
    "cout": 5,
    "description": "Permet, une fois par jour, de relancer un jet de dés impliquant l'Attribut Manuel ou Social."
  },
  {
    "id": "commercant-expertise",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Expertise",
    "cout": 2,
    "description": "Permet de confirmer ou d'infirmer l'authenticité de n'importe quel objet."
  },
  {
    "id": "commercant-faveur-politique",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Faveur politique",
    "cout": 2,
    "description": "Permet d'avoir tissé un réseau de relations politiques au sein des principales villes d'un royaume. Ce réseau s'appuie sur des amitiés, des pots de vin et des services mutuels. Le personnage pourra obtenir plus facilement certaines informations (dates, projets de lois, ragots, etc.). Ce Privilège peut être choisi plusieurs fois et s'applique à un pays à chaque fois."
  },
  {
    "id": "commercant-fournisseur-de-poisons",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Fournisseur de poisons",
    "cout": 5,
    "description": "Permet de savoir comment entrer en contact avec des intermédiaires douteux pouvant lui fournir du poison. Le meneur de jeu reste libre quant aux poisons qu'il souhaite fournir au personnage. De plus, ce Privilège est rare et ses pairs se déchargent sur lui des affaires douteuses. Si le personnage est considéré comme un criminel par les autorités, sa caste interviendra tout de même pour étouffer les poursuites mineures dont il pourra faire l'objet."
  },
  {
    "id": "commercant-notoriete",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Notoriété",
    "cout": 2,
    "description": "Permet de s'être forgé une bonne réputation au sein d'une cité ou d'une région de petite taille. La Renommée du personnage est augmentée de 1 une fois qu'il est reconnu. Le personnage gagne un bonus de 1 à toutes ses actions sociales effectuées à l'intérieur de cette cité ou région. Ce Privilège peut être acheté plusieurs fois et s'applique à une cité ou à une petite région à chaque fois."
  },
  {
    "id": "commercant-psychologie",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Psychologie",
    "cout": 2,
    "description": "Permet, après quelques minutes d'observation, de deviner l'état d'esprit d'un individu. Ce Privilège ne donne que des renseignements vagues et généraux, mais il permet tout de même de ressentir la colère, la joie, la tristesse, la fourberie, etc."
  },
  {
    "id": "commercant-reflexes-de-fuite",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Réflexes de fuite",
    "cout": 3,
    "description": "Permet, une fois par combat, de bénéficier d'une esquive gratuite, dont la Difficulté est toujours de 15."
  },
  {
    "id": "commercant-ressources",
    "caste": "commercant",
    "famille": "caste",
    "nom": "Ressources",
    "cout": 3,
    "description": "Permet de connaître des astuces, paris, expertises et de pratiquer des ventes mineures pour s'assurer un revenu régulier. Le personnage obtient 50 dracs de fer par niveau de Statut et par semaine. Il lui suffit de consacrer une heure par jour à ses menues affaires pour justifier ce revenu. Ce Privilège est suspendu lors de longs voyages en terres dépeuplées (déserts, marais, montagnes, etc.)."
  },
  {
    "id": "commercant-connaissance-du-monde",
    "caste": "commercant",
    "famille": "annexe",
    "nom": "Connaissance du monde",
    "cout": 6,
    "description": "Permet de déterminer la provenance de n'importe quel objet, vêtement, animal ou être humain, rien qu'en l'observant. De simples détails suffisent au personnage pour définir avec précision la région d'origine de ce qu'il observe."
  },
  {
    "id": "commercant-messager",
    "caste": "commercant",
    "famille": "annexe",
    "nom": "Messager",
    "cout": 4,
    "description": "Permet de disposer d'un oiseau, d'un petit animal ou d'un serviteur capable de porter des messages vers un endroit déterminé. Ce Privilège ne permet pas de communiquer, mais juste de faire acheminer des messages, écrits ou oraux, du personnage à un lieu ou à un correspondant fixe."
  },
  {
    "id": "commercant-relations-d-affaires",
    "caste": "commercant",
    "famille": "annexe",
    "nom": "Relations d'affaires",
    "cout": 6,
    "description": "Permet de disposer d'une connaissance amicale dans n'importe quelle cité comptant plus de cinq mille habitants. Cet ami a commercé fructueusement avec le personnage et pourra lui rendre des services, fournir des renseignements ou apporter une aide variée : hébergement, prêt de matériel, etc."
  },
  {
    "id": "erudit-ambassade",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Ambassade",
    "cout": 3,
    "description": "Permet de disposer d'un sceau, d'un sauf-conduit ou d'un laissez-passer officiel qui lui ouvrira les portes de nombreuses cités de Kor. En choisissant ce Privilège, le joueur devra préciser l'origine de son mandat, car il est évident qu'un document émanant de l'Empire de Solyr n'aura aucun poids d'influence en plein désert zül. Les applications de ce Privilège sont laissées à la discrétion du meneur de jeu. En contrepartie de certains avantages, le personnage peut également avoir à rendre des services ou à servir de messager officiel entre deux États."
  },
  {
    "id": "erudit-aplomb",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Aplomb",
    "cout": 1,
    "description": "Permet de contrôler ses émotions et de faire prévaloir sa condition d'érudit en toutes circonstances, quitte à aider le personnage à éviter un combat, à engager une discussion posée ou à bénéficier du respect dû à sa caste. Le personnage peut alors ajouter son Statut à son premier jet destiné à bloquer une situation en train de dégénérer. Cela peut être un jet de Diplomatie dans le cas d'une négociation tendue ou de Commandement dans le cas d'un combat sur le point de débuter."
  },
  {
    "id": "erudit-aval-draconique",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Aval draconique",
    "cout": 6,
    "description": "Permet d'être autorisé à effectuer des recherches sur l'UNE des Compétences interdites sans risque d'être inquiété. Il peut ainsi s'adonner à la Chirurgie ou à la Mécanique, ou à toute autre forme de Compétence interdite par les Dragons. Il est toujours nécessaire de posséder l'Avantage Art interdit pour développer la Compétence."
  },
  {
    "id": "erudit-calligraphie-officielle",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Calligraphie officielle",
    "cout": 4,
    "description": "Permet de rédiger des écrits très précis sur des faits ou des connaissances particulières. Ces textes enluminés selon une charte immuable ont force de preuves ou de références pour les lecteurs suivants : juristes, inquisiteurs, érudits. Ce Privilège est indispensable pour prétendre rédiger un ouvrage destiné aux générations futures et le faire figurer dans une bibliothèque. Tout autre écrit rédigé sans ce Privilège sera toujours considéré comme « douteux » par la caste des érudits. L'usage qui sera fait de ces écrits engage la réputation de toute la caste et peut entraîner des remontrances en cas d'abus."
  },
  {
    "id": "erudit-linguistique",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Linguistique",
    "cout": 2,
    "description": "Permet de maîtriser les rudiments de suffisamment de dialectes issus du langage draconique pour comprendre et se faire comprendre dans la majorité des régions de Kor sans passer de longues journées à étudier les variations locales. Ce Privilège ne permet pas de poursuivre une discussion soutenue, mais au moins d'éviter tout malentendu."
  },
  {
    "id": "erudit-memoire",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Mémoire",
    "cout": 4,
    "description": "Permet à un personnage de se remémorer un nom, une date, un événement ou une information oubliée du joueur qui l'incarne. Grâce à ce Privilège, le joueur peut demander au meneur de jeu de lui rappeler un détail vieux d'un mois à un an (en temps de jeu), selon l'importance de l'information."
  },
  {
    "id": "erudit-notoriete",
    "caste": "erudit",
    "famille": "caste",
    "nom": "Notoriété",
    "cout": 4,
    "description": "Permet de disposer des bonnes grâces d'un certain milieu social, de compter des amis fidèles au sein de la noblesse et de prétendre à certains égards liés à sa condition d'érudit. Il pourra ainsi être invité à des réunions privées, des soirées mondaines, etc. Lorsque le personnage cherche à se faire reconnaître dans son pays d'origine, il peut ajouter son Statut à sa Renommée."
  },
  {
    "id": "erudit-faveur-politique",
    "caste": "erudit",
    "famille": "annexe",
    "nom": "Faveur politique",
    "cout": 4,
    "description": "Permet d'avoir tissé un réseau de relations politiques au sein des principales villes d'un royaume. Ce réseau s'appuie sur des amitiés, du respect et des services mutuels. Le personnage pourra obtenir plus facilement certaines informations (dates, projets de lois, ragots, etc.). Ce Privilège peut être choisi plusieurs fois et s'applique à un pays à chaque fois."
  },
  {
    "id": "erudit-messager",
    "caste": "erudit",
    "famille": "annexe",
    "nom": "Messager",
    "cout": 4,
    "description": "Permet de disposer d'un oiseau, d'un petit animal dressé ou d'un serviteur capable de porter des messages vers un endroit déterminé. Ce Privilège ne permet pas de communiquer, mais juste de faire acheminer des messages, écrits ou oraux, du personnage à un lieu ou à un correspondant fixe."
  },
  {
    "id": "erudit-psychologie",
    "caste": "erudit",
    "famille": "annexe",
    "nom": "Psychologie",
    "cout": 4,
    "description": "Permet, après quelques minutes d'observation, de deviner l'état d'esprit d'un individu. Ce Privilège ne donne que des renseignements vagues et généraux, mais il permet tout de même de ressentir la colère, la joie, la tristesse, la fourberie, etc."
  },
  {
    "id": "mage-anonymat",
    "caste": "mage",
    "famille": "caste",
    "nom": "Anonymat",
    "cout": 4,
    "description": "Permet de dissimuler les marques d'appartenance à une école de magie et de bouleverser sa propre trame élémentaire pour la rendre plus difficile à ressentir. Le personnage peut passer pour un membre d'une autre caste — commerçants, voyageurs, érudits ou artisans dans la plupart des cas — ce qui peut être très utile dans certaines régions hostiles aux initiés des arcanes. Toute tentative magique pour localiser le personnage ou deviner ses émotions verra sa Difficulté augmenter de 5. Pour tenter de percer à jour cette couverture, l'interlocuteur du personnage doit réussir un jet de Social + Empathie contre une Difficulté de 20. Ce Privilège ne permet pas de connaître exactement les coutumes et usages de la caste ainsi interprétée, ce qui est du ressort de la Compétence Castes."
  },
  {
    "id": "mage-laboratoire",
    "caste": "mage",
    "famille": "caste",
    "nom": "Laboratoire",
    "cout": 5,
    "description": "Permet de disposer d'un accès privilégié aux études et aux salles d'essai des académies de magie. Le mage se fait reconnaître par le biais de ses bracelets de caste, dont les gravures sont particulières. Ce Privilège lui permet de bénéficier d'un bonus de 3 lors de ses apprentissages de sorts et de récupérer aisément des Clés banales (minéraux, métaux vulgaires, pigments, plantes, portions d'animaux...)."
  },
  {
    "id": "mage-leurre",
    "caste": "mage",
    "famille": "caste",
    "nom": "Leurre",
    "cout": 3,
    "description": "Permet de générer de façon illusoire le lancement d'un sort. Ce Privilège peut être utilisé autant de fois par jour que son niveau de Statut. Le sort simulé devra être un sort de Magie instinctive et ne fonctionnera que sur UNE cible. Le mage effectue un jet de Mental + Magie instinctive contre une Difficulté égale à Mental + Volonté de la cible. Chaque NR simule les effets normaux du sort pour un tour, pour cette cible et elle seule, cette dernière étant convaincue de voir les effets du sort. Le leurre ne coûte pas de Point de Magie, utilise autant d'actions pour être lancé et se résout comme le sort simulé. À la fin de l'effet, la cible perce l'illusion, les effets n'ayant jamais réellement existé. Le mage ne peut pas utiliser ce Privilège sur lui-même."
  },
  {
    "id": "mage-messager",
    "caste": "mage",
    "famille": "caste",
    "nom": "Messager",
    "cout": 2,
    "description": "Permet de disposer d'un oiseau, d'un petit animal ou d'un serviteur capable de porter des messages vers un endroit déterminé. Ce Privilège ne permet pas de communiquer, mais juste de faire acheminer des messages, écrits ou oraux, du personnage à un lieu ou à un correspondant fixe."
  },
  {
    "id": "mage-prevoyance",
    "caste": "mage",
    "famille": "caste",
    "nom": "Prévoyance",
    "cout": 2,
    "description": "Permet de disposer à tout moment des ingrédients non périssables et des Clés matérielles dont il risque d'avoir besoin pour lancer ses sortilèges. Ce Privilège ne prend pas en compte les ingrédients rares et extrêmement coûteux, sauf si le personnage a déjà fait la démarche nécessaire pour se les procurer — auquel cas il les a conservés sur lui."
  },
  {
    "id": "mage-sortilege-fetiche",
    "caste": "mage",
    "famille": "caste",
    "nom": "Sortilège fétiche",
    "cout": 4,
    "description": "Permet de maîtriser parfaitement la technique de lancement d'un sort. Grâce à ce Privilège, le personnage gagne un bonus de 2 chaque fois qu'il utilise ce sortilège précis. Il est possible de choisir ce Privilège deux fois."
  },
  {
    "id": "mage-style",
    "caste": "mage",
    "famille": "caste",
    "nom": "Style",
    "cout": 3,
    "description": "Permet de lancer ses sorts d'une façon non conventionnelle, en employant des postures, des Clés ou des termes inédits. Le personnage peut remplacer des postures par d'autres, des chants ou des cris par d'autres sons, ou encore utiliser des Clés matérielles différentes. Il n'est pas possible de remplacer les Clés matérielles par une posture ou un chant par un simple geste. Grâce à ce Privilège, le mage peut être facilement reconnu lorsqu'il utilise son art, ce qui lui confère une solide réputation et le fait passer pour détenteur d'un Statut supérieur. En présence d'autres mages, le personnage gagne un bonus de 1 à sa Renommée, à partir du moment où il a été reconnu."
  },
  {
    "id": "mage-tuteur",
    "caste": "mage",
    "famille": "caste",
    "nom": "Tuteur",
    "cout": 4,
    "description": "Permet de bénéficier de l'aide et de la bienveillance d'un mage de Statut supérieur, membre de la même école de magie que le personnage. Si ce mage n'est pas censé intervenir directement lors des aventures, il peut prodiguer des conseils, offrir son aide ou fournir au personnage des ingrédients rares — en échange de quelques petits services."
  },
  {
    "id": "mage-apprenti",
    "caste": "mage",
    "famille": "annexe",
    "nom": "Apprenti",
    "cout": 6,
    "description": "Permet de disposer d'un apprenti qui, en plus de rendre de menus services au personnage, pourra s'occuper de son matériel en son absence, porter des messages, colporter des rumeurs et effectuer certaines tâches de base. L'apprenti doit être instruit et demandera un peu de temps et d'attention de la part de son maître. Au bout de quelques années, l'apprenti quittera le personnage pour se lancer seul."
  },
  {
    "id": "mage-engagement",
    "caste": "mage",
    "famille": "annexe",
    "nom": "Engagement",
    "cout": 8,
    "description": "Permet d'ignorer, une fois par combat et pendant un tour complet, tous les malus découlant de ses blessures. Les malus reviennent normalement au début du tour suivant."
  },
  {
    "id": "mage-memoire",
    "caste": "mage",
    "famille": "annexe",
    "nom": "Mémoire",
    "cout": 8,
    "description": "Permet de se remémorer un nom, une date, un événement ou une information oubliée du joueur qui l'incarne. Grâce à ce Privilège, le joueur peut demander au meneur de jeu de lui rappeler un détail vieux d'un mois à un an (en temps de jeu), selon l'importance de l'information."
  },
  {
    "id": "prodige-don-d-ozyr",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don d'Ozyr",
    "cout": 3,
    "description": "Permet, en réussissant un jet de Mental + Empathie contre une Difficulté de 15, de réveiller un savoir enfoui dans l'esprit du personnage. L'origine de ce savoir est mystérieuse (à la discrétion du meneur de jeu). Lorsque ce Privilège est utilisé, l'esprit du personnage s'ouvre. Le meneur de jeu décide alors secrètement de l'information du savoir réveillé qu'il révélera au joueur à un moment critique, le personnage prenant subitement conscience de son potentiel. Ce Privilège ne peut être utilisé sur une personne avant qu'une réminiscence provoquée ne se soit révélée."
  },
  {
    "id": "prodige-don-de-brorne",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Brorne",
    "cout": 4,
    "description": "Permet, en réussissant un jet de Physique + Volonté contre une Difficulté de 15, de diviser par deux les dommages d'une attaque physique portée contre le personnage. Ce Privilège peut être utilisé trois fois par jour à ce niveau de Difficulté ; toute tentative supplémentaire se voit infliger un malus cumulatif de 5."
  },
  {
    "id": "prodige-don-de-heyra",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Heyra",
    "cout": 4,
    "description": "Permet, en réussissant un jet de Mental + Volonté contre une Difficulté de 5, de soigner une case de blessure par Niveau de Réussite, en commençant par les plus graves. Un jet réussi permet d'effacer toutes les égratignures. Ce Privilège peut être utilisé trois fois par jour, mais jamais plus d'une fois par personne. Si ce Privilège parvient à être utilisé dans le même tour où un blessé décède, cette dernière passe en coma comme si elle avait été soignée par Chirurgie. Ce Privilège n'a aucun effet si un critique entraîne une mort instantanée."
  },
  {
    "id": "prodige-don-de-kalimsshar",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Kalimsshar",
    "cout": 4,
    "description": "Permet au personnage de soigner un individu ou un animal en « transférant » une case de blessure du blessé vers lui. Ce Privilège peut être utilisé sans limitation, mais il est impossible de transférer une case de mort de cette façon."
  },
  {
    "id": "prodige-don-de-kezyr",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Kezyr",
    "cout": 4,
    "description": "Permet, deux fois par jour, de regagner tous ses Points de Maîtrise."
  },
  {
    "id": "prodige-don-de-khy",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Khy",
    "cout": 3,
    "description": "Permet, en réussissant un jet de Social + Empathie contre une Difficulté de 15, d'envoyer un message télépathique à un être humain. Le message ne peut comporter plus d'une phrase et ne peut être utilisé plus d'une fois par jour sur une même personne."
  },
  {
    "id": "prodige-don-de-kroryn",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Kroryn",
    "cout": 4,
    "description": "Permet, une fois par tour, d'augmenter de 2 la valeur d'un dé d'Initiative ou des dommages de base d'une arme contondante."
  },
  {
    "id": "prodige-don-de-nenya",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Nenya",
    "cout": 4,
    "description": "Permet, en réussissant un jet de Mental + Volonté, d'annuler les effets d'un sort visant le personnage. La Difficulté de ce jet est de 10 + 5 par niveau du sort. Ce Privilège ne peut être utilisé que trois fois par jour."
  },
  {
    "id": "prodige-don-de-szyl",
    "caste": "prodige",
    "famille": "caste",
    "nom": "Le don de Szyl",
    "cout": 3,
    "description": "Permet, une fois par combat, de lancer un dé supplémentaire d'Initiative. Il est toujours impossible de lancer plus de dés qu'un personnage ne possède de nombre d'actions."
  },
  {
    "id": "prodige-aplomb",
    "caste": "prodige",
    "famille": "annexe",
    "nom": "Aplomb",
    "cout": 2,
    "description": "Permet de contrôler ses émotions et de faire prévaloir sa condition de Prodige en toutes circonstances, aidant le personnage à éviter un combat, à engager une discussion posée ou à bénéficier du respect dû à sa caste. Le personnage peut alors ajouter son Statut à son premier jet destiné à bloquer une situation en train de dégénérer. Ce jet peut être un jet de Diplomatie dans le cas d'une négociation tendue ou de Commandement dans le cas d'un combat sur le point de débuter."
  },
  {
    "id": "prodige-engagement",
    "caste": "prodige",
    "famille": "annexe",
    "nom": "Engagement",
    "cout": 8,
    "description": "Permet d'ignorer, une fois par combat et pendant un tour complet, tous les malus découlant de ses blessures. Les malus reviennent normalement au début du tour suivant."
  },
  {
    "id": "prodige-reflexes-de-degagement",
    "caste": "prodige",
    "famille": "annexe",
    "nom": "Réflexes de dégagement",
    "cout": 6,
    "description": "Permet, une fois par combat, de bénéficier d'une esquive gratuite, dont la Difficulté est toujours de 15."
  },
  {
    "id": "protecteur-adopte",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Adopté",
    "cout": 5,
    "description": "Permet de se faire reconnaître de n'importe quel dragon, autre qu'un enfant de Kalimsshar, comme porteur de l'autorité de Brorne. Grâce à ce Privilège, le personnage pourra ainsi être autorisé à communiquer par télépathie, à demander de l'aide ou à échanger des informations avec n'importe quel dragon. Selon la situation, il lui sera éventuellement possible d'obtenir le soutien momentané du dragon ou de proposer ses services reconnus à l'allié. Si le dragon le souhaite, il pourra même le représenter dans certaines interactions avec les humains."
  },
  {
    "id": "protecteur-autorite",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Autorité",
    "cout": 4,
    "description": "Permet de faire valoir son Statut pour prendre la direction de toute investigation officielle au sein d'une cité respectant les Lois draconiques. Du moment qu'aucun protecteur de Statut supérieur n'est présent, le personnage devient responsable des enquêtes, des rapports officiels et de la gestion des éventuels messages diplomatiques."
  },
  {
    "id": "protecteur-cuirasse",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Cuirasse",
    "cout": 5,
    "description": "Permet de diviser par deux les dommages infligés par une attaque. Pour utiliser ce Privilège, le personnage doit impérativement porter une armure et annoncer qu'il ne tente aucune autre action de défense — ni esquive, ni parade. Ce Privilège ne peut être utilisé qu'une seule fois par combat et s'applique aux dégâts avant le décompte de l'armure."
  },
  {
    "id": "protecteur-defense",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Défense",
    "cout": 6,
    "description": "Permet d'effectuer une parade gratuite au bouclier par tour de combat. Cette parade ne compte pas dans le nombre d'actions du personnage et ne subit pas de Difficulté supplémentaire."
  },
  {
    "id": "protecteur-influences",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Influences",
    "cout": 3,
    "description": "Permet de disposer d'un réseau d'informateurs et de collaborateurs fidèles aux Lois draconiques, capables de lui apporter une aide non négligeable. Ce Privilège peut permettre d'obtenir des informations, de demander un soutien actif ou de disposer d'un petit nombre d'hommes de main en peu de temps. Il n'est applicable qu'au sein d'une cité comptant des groupes d'hommes et de femmes respectueux des Lois draconiques."
  },
  {
    "id": "protecteur-porte-parole",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Porte-parole",
    "cout": 3,
    "description": "Permet de faire office de porte-parole au sein de n'importe quel groupe. Le protecteur peut ainsi servir d'interlocuteur auprès de milices locales, de seigneurs ou de dirigeants de cités, négocier des trêves ou des alliances diplomatiques. La réussite de ces entreprises n'est absolument pas obligatoire, mais ce Privilège permet de prendre la parole dans des discussions que seuls les ambassadeurs attitrés sont normalement autorisés à mener."
  },
  {
    "id": "protecteur-requisition",
    "caste": "protecteur",
    "famille": "caste",
    "nom": "Réquisition",
    "cout": 4,
    "description": "Permet de réquisitionner tout matériel, renfort ou moyen financier qu'il juge indispensable au bon déroulement de sa mission. Les abus sont sévèrement punis par la caste."
  },
  {
    "id": "protecteur-engagement",
    "caste": "protecteur",
    "famille": "annexe",
    "nom": "Engagement",
    "cout": 8,
    "description": "Permet d'ignorer, une fois par combat et pendant un tour complet, tous les malus découlant de ses blessures. Les malus reviennent normalement au début du tour suivant."
  },
  {
    "id": "protecteur-notoriete",
    "caste": "protecteur",
    "famille": "annexe",
    "nom": "Notoriété",
    "cout": 4,
    "description": "Permet de s'être forgé une bonne réputation au sein d'une cité ou d'une région de petite taille. La Renommée du personnage est augmentée de 1 une fois qu'il est reconnu. Le personnage gagne un bonus de 1 à toutes ses actions sociales effectuées à l'intérieur de cette cité ou région. Ce Privilège peut être acheté plusieurs fois et s'applique à une cité ou à une petite région à chaque fois."
  },
  {
    "id": "protecteur-signes-de-bataille",
    "caste": "protecteur",
    "famille": "annexe",
    "nom": "Signes de bataille",
    "cout": 4,
    "description": "Permet de manier un langage basé sur les signes, le mouvement des yeux et les postures, afin de communiquer silencieusement des informations. Il n'y a aucun jet à effectuer, mais les informations doivent être simples (couvre-moi, attaque par le flanc, j'en vois deux, etc.) et l'interlocuteur du personnage doit obligatoirement posséder ce Privilège pour le comprendre."
  },
  {
    "id": "voyageur-archer",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Archer",
    "cout": 6,
    "description": "Permet de tirer une flèche supplémentaire lors d'un tour de combat. Cette attaque est gratuite, ne compte pas dans le nombre d'actions et n'est assortie d'aucune Difficulté supplémentaire. Son initiative est égale à celle du dé le plus faible."
  },
  {
    "id": "voyageur-compagnons",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Compagnons",
    "cout": 3,
    "description": "Permet de disposer d'une connaissance amicale dans n'importe quelle cité comptant plus de cinq mille habitants. Cet ami pourra rendre des services, fournir des renseignements ou apporter une aide variée — hébergement, prêt de matériel, etc."
  },
  {
    "id": "voyageur-connaissance-du-monde",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Connaissance du monde",
    "cout": 3,
    "description": "Permet de déterminer la provenance de n'importe quel objet, vêtement, animal ou être humain, rien qu'en l'observant. De simples détails suffisent au personnage pour définir avec précision la région d'origine de ce qu'il observe."
  },
  {
    "id": "voyageur-fils-de-la-terre",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Fils de la Terre",
    "cout": 4,
    "description": "Permet d'utiliser son environnement pour improviser un remède de fortune à n'importe quel mal — fracture, empoisonnement, paralysie, etc. En réussissant un jet de Manuel + Survie contre une Difficulté de 15, il peut annuler les effets d'un désagrément pour une période de 24 heures, après quoi l'intervention d'un soigneur ou d'un remède spécifique deviendra indispensable. Cette Difficulté peut être réduite de 5 si le personnage se trouve dans le milieu défini par sa survie, et augmentée de 5 dans un milieu différent."
  },
  {
    "id": "voyageur-logistique",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Logistique",
    "cout": 2,
    "description": "Permet de toujours disposer de croquis et de cartes sommaires détaillant les principales régions du monde. Seules les cités, les constructions et les souterrains n'ont aucune chance d'être affectés par ce Privilège."
  },
  {
    "id": "voyageur-maitrise-d-armure",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Maîtrise d'armure",
    "cout": 5,
    "description": "Permet de rendre son armure particulièrement résistante à une arme précise. Pour utiliser ce Privilège, le personnage doit obligatoirement être spécialisé dans l'arme contre laquelle il souhaite renforcer son armure. L'Indice de protection augmente de 10 face à cette arme."
  },
  {
    "id": "voyageur-rancune",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Rancune",
    "cout": 4,
    "description": "Permet de connaître les points faibles d'une catégorie d'animaux ou de créatures et de bénéficier d'un bonus de 2 points à toutes les attaques visant une créature de cette espèce. En plus de la catégorie, le personnage doit choisir le type d'attaque sur lequel s'applique ce bonus — corps à corps, armes de mêlée, armes de jet ou armes à projectiles."
  },
  {
    "id": "voyageur-solitaire",
    "caste": "voyageur",
    "famille": "caste",
    "nom": "Solitaire",
    "cout": 4,
    "description": "Permet d'agir plus efficacement lorsqu'il est seul et de gagner un bonus de 2 à ses actions de pistage, de diplomatie et de Communication."
  },
  {
    "id": "voyageur-ambassade",
    "caste": "voyageur",
    "famille": "annexe",
    "nom": "Ambassade",
    "cout": 6,
    "description": "Permet de disposer d'un sceau, d'un sauf-conduit ou d'un laissez-passer officiel qui lui ouvrira les portes de nombreuses cités de Kor. En choisissant ce Privilège, le joueur doit préciser l'origine de son mandat, car il est évident qu'un document émanant de l'Empire de Solyr n'aura aucun poids d'influence en plein désert zül. Les applications de ce Privilège sont laissées à la discrétion du meneur de jeu. En contrepartie de certains avantages, le personnage peut également avoir à rendre des services ou à servir de messager officiel entre deux États. De plus, le personnage devra conserver une position et un comportement exemplaires vis-à-vis du pays qu'il représente."
  },
  {
    "id": "voyageur-familier",
    "caste": "voyageur",
    "famille": "annexe",
    "nom": "Familier",
    "cout": 2,
    "description": "Permet de posséder un petit animal intelligent, généralement un oiseau ou un mammifère, capable d'échanger des émotions et des informations sommaires avec le personnage et de lui rendre quelques menus services (dénicher une source, flairer une piste, signaler l'approche d'humains ou de prédateurs, etc.)."
  },
  {
    "id": "voyageur-linguistique",
    "caste": "voyageur",
    "famille": "annexe",
    "nom": "Linguistique",
    "cout": 4,
    "description": "Permet de maîtriser les rudiments de suffisamment de dialectes issus du langage draconique pour comprendre et se faire comprendre dans la majorité des régions de Kor sans passer de longues journées à étudier les variations locales. Ce Privilège ne permet pas de poursuivre une discussion soutenue, mais au moins d'éviter tout malentendu."
  }
];
