// GENERATED by scripts/build-catalogs.ts from data-src/shield.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { ShieldPreset } from './shield-catalog';

export const SHIELD_CATALOG_DATA: ShieldPreset[] = [
  {
    "id": "petit-bouclier",
    "data": {
      "name": "Petit bouclier",
      "damage": "FOR + 1D10",
      "prerequisites": "FOR 3",
      "creationDifficulty": 15,
      "creationTime": 2,
      "defenseMax": 2,
      "encombrementMalus": 0,
      "special": ""
    }
  },
  {
    "id": "bouclier-renforce",
    "data": {
      "name": "Bouclier renforcé",
      "damage": "FOR + 2 + 1D10",
      "prerequisites": "FOR 4, RES 4",
      "creationDifficulty": 15,
      "creationTime": 4,
      "defenseMax": 4,
      "encombrementMalus": -2,
      "special": ""
    }
  },
  {
    "id": "grand-bouclier",
    "data": {
      "name": "Grand bouclier",
      "damage": "FOR + 4 + 1D10",
      "prerequisites": "FOR 5, RES 5",
      "creationDifficulty": 20,
      "creationTime": 6,
      "defenseMax": 6,
      "encombrementMalus": -4,
      "special": ""
    }
  },
  {
    "id": "bouclier-dragon",
    "data": {
      "name": "Bouclier dragon",
      "damage": "FOR + 5 + 1D10",
      "prerequisites": "FOR 5, RES 6",
      "creationDifficulty": 20,
      "creationTime": 5,
      "defenseMax": 7,
      "encombrementMalus": -5,
      "special": ""
    }
  },
  {
    "id": "bouclier-draconique",
    "data": {
      "name": "Bouclier draconique",
      "damage": "FOR + 5 + 1D10",
      "prerequisites": "FOR 6, RES 7",
      "creationDifficulty": 25,
      "creationTime": 2,
      "defenseMax": 8,
      "encombrementMalus": -5,
      "special": ""
    }
  }
];
