// GENERATED by scripts/build-catalogs.ts from data-src/spells.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { SpellPreset } from './spell-catalog';

export const SPELL_CATALOG_DATA: SpellPreset[] = [
  {
    "id": "bouclier-carmin",
    "data": {
      "name": "Bouclier carmin",
      "level": 1,
      "complexity": 15,
      "discipline": "magieInstinctive",
      "sphere": "sphereFeu",
      "cost": 3,
      "castTimeAmount": 2,
      "castTimeUnit": "action",
      "difficulty": 15,
      "cle": "Morceau de charbon, chant du feu",
      "effect": "Pare une attaque. Disparait après (1 + NR) heures si non dissipé."
    }
  },
  {
    "id": "file-vent",
    "data": {
      "name": "File vent",
      "level": 1,
      "complexity": 20,
      "discipline": "magieInstinctive",
      "sphere": "sphereVents",
      "cost": 5,
      "castTimeAmount": 1,
      "castTimeUnit": "action",
      "difficulty": 15,
      "cle": "Rune de vitesse, mouvements très vifs et saccadés",
      "effect": "-5 jets d'esquive et +10 difficulté des attaques adverses. Pendant (1 + NR) tours."
    }
  }
];
