// GENERATED by scripts/build-catalogs.ts from data-src/statuses.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { StatutPreset } from './status-catalog';

export const STATUS_CATALOG_DATA: StatutPreset[] = [
  {
    "caste": "artisan",
    "niveau": 1,
    "nom": "Apprenti",
    "requis": "une Compétence d'Artisanat à 6, Manuel à 4",
    "benefice": "Le personnage peut développer une Spécialisation de Technique.",
    "technique": {
      "nom": "D'un compagnon à l'autre",
      "effet": "En réussissant un jet de Mental + Artisanat approprié contre une Difficulté de 10, le personnage peut déterminer l'âge, la qualité et le mode de fonctionnement de tout objet manufacturé. Chaque NR lui confère une information supplémentaire."
    },
    "note": ""
  },
  {
    "caste": "artisan",
    "niveau": 2,
    "nom": "Compagnon",
    "requis": "une Compétence d'Artisanat à 7, 40 points dans les Compétences Manuelles, Manuel à 5, Maîtrise à 4, Tendance Homme à 1, 2 Privilèges de caste",
    "benefice": "Le personnage peut développer la Discipline de magie Sorcellerie comme si elle lui était réservée, ainsi qu'une Sphère en rapport avec son artisanat principal, du moment qu'il y trouve un intérêt.",
    "technique": {
      "nom": "La voie du progrès",
      "effet": "En réussissant un jet de Manuel + Coordination contre une Difficulté de 10, le personnage peut comprendre le fonctionnement et utiliser n'importe quel objet mécanique comme s'il possédait la Compétence appropriée à un niveau égal à la moitié de son Attribut Manuel (arrondi au supérieur)."
    },
    "note": ""
  },
  {
    "caste": "artisan",
    "niveau": 3,
    "nom": "Artisan",
    "requis": "trois Compétences Techniques à 7, 50 points dans les Compétences Manuelles, Manuel à 6, Maîtrise à 6, Tendance Homme ou Dragon à 2, 4 Privilèges de caste",
    "benefice": "Chaque fois qu'il fait appel aux Tendances, le personnage peut dépenser 1 Point de Chance pour relancer le dé de l'Homme.",
    "technique": {
      "nom": "L'essence de l'art",
      "effet": "Le personnage a la capacité d'améliorer des objets manufacturés dont il possède une connaissance précise. Il doit tout d'abord effectuer un jet d'Intelligence + Artisanat contre une Difficulté de 5 pour déterminer le temps de travail nécessaire. La durée est de 30 + 1D10 jours, mais chaque NR réduit ce délai de 10 jours. Ensuite, il doit réussir un jet de Manuel + Empathie contre une Difficulté de 15 pour conférer à l'objet un bonus définitif égal à 1 + nombre de NR. Ce bonus peut s'appliquer à l'efficacité ou à la maniabilité d'une arme (bonus aux dommages ou au toucher), ainsi qu'à toutes sortes d'outils, d'instruments et de mécanismes connus du personnage. Une seule amélioration du même type est possible par arme, et chaque nouvelle amélioration augmente de 5 la Difficulté de ces jets."
    },
    "note": ""
  },
  {
    "caste": "artisan",
    "niveau": 4,
    "nom": "Maître Artisan",
    "requis": "une Compétence d'Artisanat à 10, deux Compétences Pratiques à 6, 60 points dans les Compétences Manuelles, Manuel à 7, Tendance Homme ou Dragon à 3, 5 Privilèges de caste",
    "benefice": "Le personnage peut apprendre les sorts de Magie instinctive et de Sorcellerie au même coût que les mages.",
    "technique": {
      "nom": "L'esquisse du destin",
      "effet": "La maîtrise du personnage est telle qu'il peut inventer des méthodes de travail auxquelles nul n'aurait jamais songé. Il doit pour cela réussir un jet d'Intelligence + Compétence contre une Difficulté de 15 pour chaque Compétence nécessaire à la réalisation de l'objet (par exemple, Armes mécaniques et Forge pour créer une arbalète). La somme de tous les NR vient ensuite s'ajouter au bonus du jet de Manuel + Artisanat que le joueur doit réussir contre une Difficulté variant en fonction de la complexité, de la taille et de l'efficacité de l'objet. Si un seul de ces jets est raté, la création échoue."
    },
    "note": ""
  },
  {
    "caste": "artisan",
    "niveau": 5,
    "nom": "Grand Maître Artisan",
    "requis": "une Compétence d'Artisanat à 12, trois Compétences Pratiques à 6, Manuel à 9, Tendance Homme ou Dragon à 4, 5 Privilèges de caste",
    "benefice": "À chacun de ses jets, le personnage lance et conserve un dé supplémentaire de l'Homme qui ne lui rapporte aucun Point de Tendance, et ce quelle que soit son affiliation.",
    "technique": {
      "nom": "La force du rouage",
      "effet": "En dépensant 1 Point de Maîtrise, le personnage peut utiliser son Attribut Manuel à la place de n'importe quel autre Attribut. Si le jet est réussi, il le regagne aussitôt."
    },
    "note": "À ce Statut, les artisans se présentent généralement comme les Maîtres de leur art (Maître Forgeron, par exemple). Il n'y a qu'un seul Maître par voie."
  },
  {
    "caste": "artisan",
    "niveau": 1,
    "nom": "Apprenti noir",
    "requis": "une Compétence d'Artisanat à 6, Manuel à 3",
    "benefice": "Le personnage peut développer une spécialisation de Compétence Technique.",
    "technique": {
      "nom": "D'un compagnon à l'autre",
      "effet": "En réussissant un jet de Mental + Artisanat approprié contre une Difficulté de 10, le personnage peut déterminer l'âge, la qualité et le mode de fonctionnement de tout objet manufacturé. Chaque Niveau de Réussite lui confère une information supplémentaire."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "artisan",
    "niveau": 2,
    "nom": "Compagnon noir",
    "requis": "une Compétence d'Artisanat à 7, Manuel à 4, 40 points en Compétences Manuelles",
    "benefice": "Le personnage peut développer n'importe quelle Compétence Manuelle humaniste à un niveau maximum égal à son Attribut Mental + 2, du moment qu'il trouve un professeur.",
    "technique": {
      "nom": "La voie du progrès",
      "effet": "En réussissant un jet de Mental + Coordination contre une Difficulté de 10, le personnage peut comprendre le fonctionnement de n'importe quel objet mécanique et l'utiliser comme s'il possédait la Compétence appropriée à un niveau égal à la moitié de son Attribut Manuel (arrondi au supérieur)."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "artisan",
    "niveau": 3,
    "nom": "Artisan noir",
    "requis": "une Compétence d'Artisanat à 8, Manuel à 5, 60 points en Compétences Manuelles",
    "benefice": "Chaque fois qu'il fait appel aux Tendances, le personnage peut dépenser 1 Point de Chance pour relancer le dé de l'Homme ou de la Fatalité.",
    "technique": {
      "nom": "Puissance de l'émotion",
      "effet": "L'artisan noir retire une émotion particulière des œuvres d'art ou d'artisanat. Si elle correspond à la situation et s'il réussit un jet de Mental + Empathie Difficulté 5, l'artisan noir gagne un bonus égal à 1 + Niveaux de Réussite pour un jet unique. Par exemple, épée et violence lors d'un combat, sculpture et charme pour un rendez-vous galant devant une fontaine de marbre taillé. Cette Technique ne peut être utilisée qu'une unique fois par objet et (niveau de Statut) fois par jour."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "artisan",
    "niveau": 4,
    "nom": "Maître Artisan noir",
    "requis": "une Compétence d'Artisanat à 10, Manuel à 6, 70 points en Compétences Manuelles",
    "benefice": "Le personnage est capable de comprendre le fonctionnement de n'importe quel mécanisme rien qu'en le touchant. Il peut ainsi déclencher ou désamorcer toutes sortes de pièges, ôter la pièce indispensable d'un rouage, saboter une arme complexe.",
    "technique": {
      "nom": "Simulacre de vie",
      "effet": "L'artisan noir, en sacrifiant un Point de Maîtrise (qui peut être récupéré via Points d'Expérience), insuffle le mouvement à une œuvre. Cette Technique permet aux non-mages de réaliser des œuvres enchantées sans user de Sphères. Il n'est pas possible de créer un service ou un serviteur par ce moyen : l'œuvre agit uniquement en fonction de ce qu'elle représente. Par exemple, dans un tableau bucolique, les cygnes nagent dans le lac, tandis que les enfants jouent sur la rive, la statue d'un athlète prend des poses et effectue des mouvements typiques de son activité. Cela peut surprendre une personne non prévenue."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "artisan",
    "niveau": 5,
    "nom": "Maître Artisan noir",
    "requis": "une Compétence d'Artisanat à 10+, Manuel à 8, 80 points en Compétences Manuelles",
    "benefice": "À chacun de ses jets, le personnage lance et conserve un dé supplémentaire de l'Homme qui ne lui rapporte aucun Point de Tendance, et ce, quelle que soit son affiliation.",
    "technique": {
      "nom": "La force du rouage",
      "effet": "En dépensant 1 Point de Maîtrise, le personnage peut utiliser son Attribut Manuel à la place de n'importe quel autre Attribut. Si le jet est réussi, il ne regagne aucun Point de Maîtrise."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "combattant",
    "niveau": 1,
    "nom": "Apprenti",
    "requis": "une Compétence d'arme à 6, Physique à 4",
    "benefice": "Le personnage peut développer une Spécialisation de Combat.",
    "technique": {
      "nom": "L'œil du maître",
      "effet": "En réussissant un jet de Mental + Compétence d'arme de l'adversaire contre une Difficulté de 10, le personnage peut déterminer si le niveau de Compétence d'arme de son adversaire est inférieur, supérieur ou égal au sien. Chaque Niveau de Réussite peut lui donner une indication sur la technique utilisée (botte secrète, Technique spéciale, etc.)."
    },
    "note": ""
  },
  {
    "caste": "combattant",
    "niveau": 2,
    "nom": "Spadassin",
    "requis": "une Compétence d'arme à 8, Physique à 5, Maîtrise à 4, 30 points dans les Compétences Physiques, une Tendance à 2, 3 Privilèges de caste",
    "benefice": "Le personnage peut posséder jusqu'à trois Spécialisations : deux d'une même catégorie et une d'une autre catégorie.",
    "technique": {
      "nom": "La main du maître",
      "effet": "Une fois par combat, le personnage peut ajouter la valeur de son Attribut Physique au résultat de l'un de ses dés d'Initiative, du moment qu'il annonce l'utilisation de cette Technique avant de lancer ses dés."
    },
    "note": ""
  },
  {
    "caste": "combattant",
    "niveau": 3,
    "nom": "Combattant",
    "requis": "une Compétence d'arme à 9, deux Compétences d'arme à 6, Physique à 6, Maîtrise à 6, 40 points dans les Compétences Physiques, une Tendance à 3, 4 Privilèges de caste",
    "benefice": "Le personnage peut porter une attaque supplémentaire sans pénalité à chaque tour de combat.",
    "technique": {
      "nom": "La puissance du maître",
      "effet": "Lorsqu'il combat avec une arme dans laquelle il s'est spécialisé, le personnage lance un dé supplémentaire pour déterminer les dommages."
    },
    "note": ""
  },
  {
    "caste": "combattant",
    "niveau": 4,
    "nom": "Maître d'armes",
    "requis": "une Compétence d'arme à 10, Physique à 7, Manuel à 5, Maîtrise à 8, Coordination à 6, 45 points dans les Compétences Physiques, une Tendance à 4, 6 Privilèges de caste",
    "benefice": "Lorsqu'il combat un adversaire maniant une arme utilisant la même Compétence que celle (ou celles) dans laquelle il s'est spécialisé, le personnage gagne un bonus de 2 à tous ses jets d'attaque et de parade.",
    "technique": {
      "nom": "La voie du maître",
      "effet": "Lorsqu'il combat, le personnage n'est pas soumis à la règle des Tendances et peut conserver n'importe quel dé sans gagner ni perdre de Points de Tendance (sauf dans le cas d'une réussite critique)."
    },
    "note": ""
  },
  {
    "caste": "combattant",
    "niveau": 5,
    "nom": "Grand maître d'armes",
    "requis": "une Compétence d'arme à 12, Physique à 8, Maîtrise à 10, 50 points dans les Compétences Physiques, une Tendance à 5",
    "benefice": "La Difficulté de tous ses jets de combat est réduite de 5 lorsque le personnage utilise son arme de prédilection. De plus, il ne peut être ni désarmé, ni abusé par une feinte d'arme de la même famille que la sienne.",
    "technique": {
      "nom": "La maîtrise parfaite",
      "effet": "Le personnage ne peut subir d'échec critique lorsqu'il utilise son arme de prédilection. Tous les « 1 » obtenus sur un jet de combat sont donc relancés."
    },
    "note": "À ce Statut, les combattants peuvent tenter de devenir Maître de l'arme dont ils ont fait leur spécialité (Maître des Épées, par exemple). Il n'existe qu'un seul Maître par famille d'armes parmi les Grands Maîtres d'Armes, et l'obtention de ce titre passe par un duel public."
  },
  {
    "caste": "combattant",
    "niveau": 1,
    "nom": "Apprenti noir",
    "requis": "une Compétence d'arme à 6, Physique à 4",
    "benefice": "Le personnage peut développer une spécialisation de Combat.",
    "technique": {
      "nom": "L'œil du maître",
      "effet": "En réussissant un jet de Mental + Compétence d'arme de l'adversaire contre une Difficulté de 10, le personnage peut déterminer si le niveau de Compétence de son adversaire est inférieur, supérieur ou égal au sien. Chaque Niveau de Réussite peut lui donner une indication sur la technique utilisée (botte secrète, Technique spéciale, etc.)."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "combattant",
    "niveau": 2,
    "nom": "Spadassin noir",
    "requis": "une Compétence d'arme à 8, Physique à 5, 30 points dans les Compétences Physiques",
    "benefice": "Le personnage peut posséder deux spécialisations de Combat.",
    "technique": {
      "nom": "La main du maître",
      "effet": "Une fois par combat, le personnage peut ajouter la valeur de son Attribut Physique au résultat de l'un de ses dés d'Initiative, du moment qu'il annonce l'utilisation de cette Technique avant de lancer les dés."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "combattant",
    "niveau": 3,
    "nom": "Combattant noir",
    "requis": "une Compétence d'arme à 9, Physique à 6, 40 points dans les Compétences Physiques",
    "benefice": "Le personnage peut porter une attaque supplémentaire sans pénalité à chaque tour de combat.",
    "technique": {
      "nom": "Le coup du maître",
      "effet": "Lorsqu'il combat avec une arme dans laquelle il s'est spécialisé et qu'il obtient une réussite critique, le personnage peut dépenser des Points de Chance ou de Maîtrise pour les ajouter au jet sur la table des critiques. Il peut au maximum dépenser autant de points que son niveau de Statut et tous ces points doivent être du même Attribut mineur."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "combattant",
    "niveau": 4,
    "nom": "Maître d'armes noir",
    "requis": "une Compétence d'arme à 10, Physique à 7, 50 points dans les Compétences Physiques",
    "benefice": "Lorsqu'il combat un adversaire maniant une arme utilisant la même Compétence que celle dans laquelle (ou lesquelles) il s'est spécialisé, le personnage gagne un bonus de 2 points à tous ses jets d'attaque et de parade.",
    "technique": {
      "nom": "La voie du maître",
      "effet": "Lorsqu'il combat, le personnage n'est pas soumis à la règle des Tendances et peut conserver n'importe quel dé sans gagner ni perdre de Points de Tendance (sauf dans le cas d'une réussite critique)."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "combattant",
    "niveau": 5,
    "nom": "Grand Maître d'armes noir",
    "requis": "une Compétence d'arme à 10+, Physique à 8, 60 points dans les Compétences Physiques",
    "benefice": "La Difficulté de tous les jets de combat est réduite de 5 lorsque le personnage utilise son arme de prédilection. De plus, il ne peut être ni désarmé, ni abusé par une feinte d'arme de la même famille que la sienne.",
    "technique": {
      "nom": "La maîtrise parfaite",
      "effet": "Le personnage ne peut subir d'échec critique lorsqu'il utilise son arme de prédilection. Tous les « 1 » obtenus sur un jet de combat sont donc relancés."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "commercant",
    "niveau": 1,
    "nom": "Marchand",
    "requis": "20 points dans les Compétences Sociales, Présence à 4, Social à 4, Tendance Homme à 2",
    "benefice": "Le personnage débute sa carrière avec une somme de 500 dracs d'argent et peut développer une Spécialisation de Communication ou de Manipulation.",
    "technique": {
      "nom": "Le sourire accueillant",
      "effet": "En réussissant un jet de Social + Empathie contre une Difficulté de 15, le personnage peut deviner ce que pense un individu dans la ville où il se trouve. Si cette raison est secrète, le personnage doit réussir un jet de Social + Présence contre une Difficulté de 20 pour obtenir la même information."
    },
    "note": ""
  },
  {
    "caste": "commercant",
    "niveau": 2,
    "nom": "Commerçant",
    "requis": "25 points dans les Compétences Sociales, Marchandage ou Baratin à 6, 2 Privilèges de caste",
    "benefice": "Le personnage dispose d'un petit comptoir marchand, situé dans une cité de son choix, et de quelques apprentis capables de gérer son commerce en son absence.",
    "technique": {
      "nom": "Recommencer sur erreur",
      "effet": "Une fois par jour, en dépensant tous ses Points de Chance restants (minimum 1), le personnage peut transformer un échec critique en un échec simple."
    },
    "note": ""
  },
  {
    "caste": "commercant",
    "niveau": 3,
    "nom": "Négociant",
    "requis": "35 points dans les Compétences Sociales, Chance à 4, 3 Privilèges de caste et de bonnes réserves d'or et de biens (environ 500 dracs d'or)",
    "benefice": "Le personnage connaît le nom et les principales caractéristiques de toutes les compagnies commerciales, guildes et factions marchandes de son royaume. Dans le cas d'un groupe récemment créé, il peut effectuer un jet de Social + Vie en cité contre une Difficulté de 15, ou 20 dans le cas d'une compagnie secrète, pour obtenir ces mêmes informations.",
    "technique": {
      "nom": "L'examen de conscience",
      "effet": "Chaque fois qu'il le désire, le personnage peut effacer tous ses cercles de Tendance, du moment qu'il vient de faire une bonne affaire."
    },
    "note": ""
  },
  {
    "caste": "commercant",
    "niveau": 4,
    "nom": "Dignitaire",
    "requis": "Diplomatie, Estimation et Lois à 6, Chance à 6, 5 Privilèges de caste et une importante fortune matérielle (au moins 1000 dracs d'or)",
    "benefice": "Pour tous ses jets de Social ou de Manuel, le personnage lance un dé supplémentaire de l'Homme qu'il peut choisir de conserver à la place de n'importe quel autre. De plus, il gagne un bonus de 1 à tous ses jets de Social effectués dans sa cité d'origine, ou dans celle où se trouve son comptoir principal.",
    "technique": {
      "nom": "Une technique éprouvée",
      "effet": "Une fois par jour, en dépensant 3 Points de Chance, le personnage peut doubler la valeur de son Attribut Manuel ou Social pour effectuer une action. Aucun Point de Maîtrise ou de Chance ne peut être regagné de cette façon."
    },
    "note": ""
  },
  {
    "caste": "commercant",
    "niveau": 5,
    "nom": "Prince marchand",
    "requis": "60 points dans les Compétences Sociales, Chance ou Maîtrise à 8, un véritable empire commercial",
    "benefice": "Le personnage est à ce point psychologue qu'il sait toujours si on lui ment. En réussissant un jet de Social + Empathie contre une Difficulté de 15, ou de 20 pour un dragon, il peut également apprendre la vérité sans le montrer à son interlocuteur.",
    "technique": {
      "nom": "Le bénéfice du doute",
      "effet": "Une fois par jour, le personnage peut effacer de la mémoire d'un individu tout souvenir le concernant, du moment qu'il n'a eu aucun contact physique avec cette personne. La durée du souvenir ne peut excéder un nombre de minutes égal à la valeur de l'Attribut Social du personnage. Une fois l'« entretien » terminé, l'individu ne se doute même pas qu'il a rencontré le personnage."
    },
    "note": ""
  },
  {
    "caste": "commercant",
    "niveau": 1,
    "nom": "Marchand noir",
    "requis": "Social à 3, 20 points dans les Compétences Sociales",
    "benefice": "Le personnage débute sa carrière avec une somme de 500 dracs d'argent.",
    "technique": {
      "nom": "Le sourire accueillant",
      "effet": "En réussissant un jet de Social + Empathie contre une Difficulté de 15, le personnage peut deviner ce qui amène un individu dans la ville où il se trouve. Si cette raison est secrète, le personnage doit réussir un jet de Social + Empathie contre une Difficulté de 20 pour obtenir la même information."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "commercant",
    "niveau": 2,
    "nom": "Commerçant noir",
    "requis": "Présence ou Empathie à 6, 30 points dans les Compétences Sociales",
    "benefice": "Le personnage dispose d'un abri secret, dans la cité de son choix, comprenant une entrée normale et au maximum deux passages secrets.",
    "technique": {
      "nom": "Reconnaître son erreur",
      "effet": "Une fois par jour, en dépensant tous ses Points de Chance restants (minimum 1), le personnage peut transformer un échec critique en un échec simple."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "commercant",
    "niveau": 3,
    "nom": "Négociant noir",
    "requis": "Social à 5, 50 points dans les Compétences Sociales",
    "benefice": "Le personnage connaît le nom et les principales caractéristiques de toutes les compagnies commerciales, guildes et factions marchandes de son royaume. Dans le cas d'un groupe récemment créé, il peut effectuer un jet de Social + Vie en cité contre une Difficulté de 15, ou de 20, dans le cas d'une compagnie secrète, pour obtenir ces mêmes informations.",
    "technique": {
      "nom": "L'examen de conscience",
      "effet": "Chaque fois qu'il le désire, le personnage peut effacer tous ses cercles de Tendances, du moment qu'il vient de faire une bonne affaire."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "commercant",
    "niveau": 4,
    "nom": "Dignitaire noir",
    "requis": "Présence ou Empathie à 8, 60 points dans les Compétences Sociales",
    "benefice": "Pour tous ses jets de Social ou de Manuel, le personnage lance un dé supplémentaire de la Tendance Homme ou Fatalité, qu'il peut choisir de conserver à la place de n'importe quel autre. De plus, il gagne un bonus de 1 à tous ses jets de Social effectués dans sa cité d'origine, ou dans celle où se trouve son abri principal.",
    "technique": {
      "nom": "Une technique éprouvée",
      "effet": "Une fois par jour, en dépensant 3 Points de Chance, le personnage peut doubler la valeur de son Attribut Manuel ou Social pour effectuer une action. Aucun Point de Maîtrise ou de Chance ne peut être regagné de cette façon."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "commercant",
    "niveau": 5,
    "nom": "Prince Marchand noir",
    "requis": "Social à 7, 70 points dans les Compétences Sociales",
    "benefice": "Le personnage est à ce point psychologue qu'il sait toujours si on lui ment. En réussissant un jet de Social + Empathie contre une Difficulté de 15, ou de 20 pour un dragon, il peut également apprendre la vérité sans le montrer à son interlocuteur.",
    "technique": {
      "nom": "Le bénéfice du doute",
      "effet": "Une fois par jour, le personnage peut effacer de la mémoire d'un individu tout souvenir le concernant, du moment qu'il n'a eu aucun contact physique avec cette personne. La durée du souvenir ne peut excéder un nombre de minutes égal à la valeur de l'Attribut Social du personnage. Une fois « l'entretien » terminé, l'individu ne se doute même pas qu'il a rencontré le personnage."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "erudit",
    "niveau": 1,
    "nom": "Apprenti",
    "requis": "une Compétence Théorique à 6, Mental à 4",
    "benefice": "Le personnage peut se spécialiser dans une Compétence Mentale de son choix.",
    "technique": {
      "nom": "La lettre et le nom",
      "effet": "Du moment qu'il a déjà lu un écrit, le personnage est capable d'en reconnaître l'auteur sans effectuer le moindre jet."
    },
    "note": ""
  },
  {
    "caste": "erudit",
    "niveau": 2,
    "nom": "Initié",
    "requis": "une Compétence Théorique à 8, Mental à 5, Intelligence à 5, Maîtrise à 4, 35 points cumulés dans les Compétences Mentales, une Tendance à 2, 3 Privilèges de caste",
    "benefice": "Le personnage dispose d'un certain prestige et peut influer sur les convictions des citoyens de statut inférieur ou égal au sien. En engageant une discussion philosophique d'une heure, il peut dépenser deux cercles d'une Tendance pour déplacer chez son interlocuteur un cercle d'une Tendance vers celle qu'il a dépensée.",
    "technique": {
      "nom": "La rune et le secret",
      "effet": "En réussissant un jet de Mental + Lire et écrire contre une Difficulté de 15, le personnage peut déterminer l'origine, la date ou le sens général de n'importe quel ouvrage écrit (y compris les symboles, les runes et les motifs divers). Chaque NR lui donne une de ces trois informations."
    },
    "note": ""
  },
  {
    "caste": "erudit",
    "niveau": 3,
    "nom": "Érudit",
    "requis": "une Compétence Théorique à 9, deux Compétences Théoriques à 7, Mental à 6, Intelligence à 6, Maîtrise à 4, 45 points dans les Compétences Mentales, une Tendance à 3, 4 Privilèges de caste",
    "benefice": "Le personnage lance pour tous ses jets de Mental un dé neutre supplémentaire qu'il rajoute au résultat du dé choisi.",
    "technique": {
      "nom": "L'homme et l'Étoile",
      "effet": "Par son seul regard, le personnage peut déterminer si un individu est touché par une Étoile. En réussissant un jet de Mental + Empathie contre une Difficulté de 10, il peut découvrir une des Motivations de l'Étoile pour chaque NR."
    },
    "note": ""
  },
  {
    "caste": "erudit",
    "niveau": 4,
    "nom": "Sage",
    "requis": "une Compétence Théorique à 10, trois Compétences Théoriques à 8, Mental à 7, 50 points dans les Compétences Mentales, 2 Spécialisations Mentales, 5 Privilèges de caste",
    "benefice": "Le personnage est considéré comme un disciple d'Ozyr. À ce titre, il représente la sagesse et la connaissance du Grand Dragon des Océans, et peut être consulté lors des discussions de la plus grande importance — conseils de guerre, alliances politiques, etc.",
    "technique": {
      "nom": "Le livre et le temps",
      "effet": "Une fois par jour, en réussissant un jet de Mental + Chance contre une Difficulté de 15, le personnage peut se souvenir d'un texte et obtenir des informations sur n'importe quel sujet traité par l'écrit (histoire, légende, géographie, science, etc.)."
    },
    "note": ""
  },
  {
    "caste": "erudit",
    "niveau": 5,
    "nom": "Prophète",
    "requis": "une Compétence Théorique à 12, Mental à 8, Intelligence à 8, Maîtrise à 8, une Tendance à 4, 70 points dans les Compétences Mentales, 6 Privilèges de caste",
    "benefice": "Le personnage est autorisé à consulter les écrits de n'importe quelle bibliothèque draconique. Lorsqu'il y fait des recherches, la Difficulté de tous les jets impliquant des Compétences Théoriques est réduite de 5.",
    "technique": {
      "nom": "L'homme et le destin",
      "effet": "Le personnage est tellement en phase avec le monde qu'il peut lire dans le destin comme dans un livre. Une fois par jour, il peut interroger les astres pour obtenir une réponse à l'une des questions qu'il se pose sur son avenir ou celui de ses compagnons."
    },
    "note": ""
  },
  {
    "caste": "erudit",
    "niveau": 1,
    "nom": "Apprenti noir",
    "requis": "une Compétence Théorique à 6, Mental à 4",
    "benefice": "Le personnage peut se spécialiser dans une Compétence Théorique de son choix.",
    "technique": {
      "nom": "La lettre et le nom",
      "effet": "Du moment qu'il a déjà lu un écrit, le personnage est capable d'en reconnaître l'auteur sans effectuer de jet."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "erudit",
    "niveau": 2,
    "nom": "Initié noir",
    "requis": "une Compétence Théorique à 8, Mental à 5, 30 points dans les Compétences Théoriques",
    "benefice": "Par un jet de Mental + Empathie contre une Difficulté de (Volonté de la cible x 3), le personnage peut discerner si un interlocuteur est actuellement tenté par la transgression d'Interdits, de lois ou d'Édits (ou s'il est en train de le faire).",
    "technique": {
      "nom": "La rune et le secret",
      "effet": "En réussissant un jet de Mental + Lire et écrire contre une Difficulté de 15, le personnage peut déterminer l'origine, la date ou le sens général de n'importe quel ouvrage écrit (y compris les symboles, les runes et les motifs divers). Chaque Niveau de Réussite lui donne une de ces trois informations."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "erudit",
    "niveau": 3,
    "nom": "Érudit noir",
    "requis": "une Compétence Théorique à 9, Intelligence à 6, 40 points dans les Compétences Théoriques",
    "benefice": "Le personnage lance un dé de neutre pour tous ses jets de Mental qu'il rajoute au résultat du dé choisi.",
    "technique": {
      "nom": "L'homme et l'étoile",
      "effet": "Par son seul regard, le personnage peut déterminer si le personnage est touché par une Étoile. En réussissant un jet de Mental + Empathie contre une Difficulté de 10, il peut découvrir une des Motivations de l'Étoile pour chaque Niveau de Réussite."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "erudit",
    "niveau": 4,
    "nom": "Sage noir",
    "requis": "une Compétence Théorique à 10, Mental à 6, 60 points dans les Compétences Théoriques",
    "benefice": "En tant que disciple de Kalimsshar, le Sage noir ressent intuitivement les rapports de force entre individus. Il discerne automatiquement les tensions, les alliances et les intérêts des groupes d'individus.",
    "technique": {
      "nom": "Le livre et le temps",
      "effet": "Une fois par jour, en réussissant un jet de Mental + Chance contre une Difficulté de 15, le personnage peut se souvenir d'un texte et obtenir des informations sur n'importe quel sujet traité par l'écrit (histoire, légende, géographie, science, etc.)."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "erudit",
    "niveau": 5,
    "nom": "Prophète noir",
    "requis": "une Compétence Théorique à 10+, Mental à 7, Intelligence à 8, 70 points dans les Compétences Théoriques",
    "benefice": "En appelant à la source du pouvoir de Kalimsshar, le Prophète noir peut poser une question précise à l'auteur de n'importe quel écrit qu'il détient. Ce Bénéfice force l'esprit désincarné de l'auteur à y répondre. Il ne peut utiliser ce Bénéfice qu'une fois par jour, et une unique fois par écrit.",
    "technique": {
      "nom": "L'homme et le destin",
      "effet": "Le personnage est tellement en phase avec le monde qu'il peut lire dans le destin comme dans un livre. Une fois par jour, comme le ferait un Oracle, il peut interroger les astres pour obtenir une réponse à l'une des questions qu'il se pose sur son avenir ou celui de ses compagnons."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "mage",
    "niveau": 1,
    "nom": "Apprenti",
    "requis": "une Sphère à 4, une Discipline à 5, Mental à 4, Intelligence à 4",
    "benefice": "Le personnage peut lire les matrices magiques et déchiffrer les bracelets de mage pour en reconnaître les domaines d'influence grâce à leurs couleurs, leurs matières, leurs gravures, etc. Il peut développer une Spécialisation de Combat ou de Théorie.",
    "technique": {
      "nom": "La matière",
      "effet": "Pour chaque Sphère qu'il maîtrise, le personnage peut faire apparaître, une fois par jour, un petit volume d'élément qu'il pourra ensuite façonner ou utiliser à sa guise. Il peut s'agir d'une petite flamme, d'une poignée de terre, d'un litre d'eau pure, etc."
    },
    "note": ""
  },
  {
    "caste": "mage",
    "niveau": 2,
    "nom": "Initié",
    "requis": "une Sphère à 5, une Discipline à 6, Mental à 5, Intelligence à 5, 5 sorts de niveau 1",
    "benefice": "En réussissant un jet de Mental + Intelligence contre une Difficulté de 15, le personnage peut reconnaître un sort lancé par un autre mage. Si le sort utilise sa Sphère privilégiée, la Difficulté de ce jet est réduite de 5.",
    "technique": {
      "nom": "L'esprit",
      "effet": "Chaque jour, le personnage dispose de deux NR gratuits qu'il peut utiliser pour augmenter les effets de n'importe quel sort (portée, dommages, précision, etc.). Ces bonus peuvent s'appliquer sur deux sorts différents ou pour améliorer deux effets d'un même sort. S'ils ne sont pas dépensés, ils sont tout simplement perdus."
    },
    "note": ""
  },
  {
    "caste": "mage",
    "niveau": 3,
    "nom": "Mage",
    "requis": "une Sphère à 6, deux Sphères à 3, deux Disciplines à 5, Mental à 6, Maîtrise à 4, Intelligence à 6, 4 sorts de niveau 2, 3 Privilèges de caste",
    "benefice": "Le personnage est désormais autorisé à concevoir ses propres sorts, à les enseigner et à créer des matrices magiques pour répandre son savoir. Ce bénéfice évite ainsi que de trop jeunes mages ne s'essayent à la dangereuse conception d'un sort.",
    "technique": {
      "nom": "La volonté",
      "effet": "En dépensant 2 Points de Maîtrise et 2 Points de Magie, le personnage peut lancer et conserver un dé supplémentaire pour effectuer n'importe quel jet de Discipline magique. Ce dé neutre n'est pas concerné par la règle des Tendances."
    },
    "note": ""
  },
  {
    "caste": "mage",
    "niveau": 4,
    "nom": "Grand mage",
    "requis": "une Sphère à 8, trois Sphères à 4, une Discipline à 8, Maîtrise à 6, Intelligence à 7, 3 sorts de niveau 3, 5 Privilèges de caste",
    "benefice": "Le personnage ajoute le niveau de chacune de ses Sphères à tous ses jets de défense contre les sorts utilisant la Sphère correspondante.",
    "technique": {
      "nom": "La flamme",
      "effet": "Une fois par combat, le personnage peut lancer un sort de Magie instinctive sans dépenser aucun Point de Magie."
    },
    "note": ""
  },
  {
    "caste": "mage",
    "niveau": 5,
    "nom": "Grand Maître",
    "requis": "une Sphère ou une Discipline à 10, trois Sphères à 6, deux Disciplines à 7, Mental à 7, Maîtrise à 6, 25 sorts, 6 Privilèges de caste",
    "benefice": "Le personnage est immunisé aux effets des sorts de niveau 1 de sa Sphère privilégiée (à choisir lors de son accession à ce Statut parmi les Sphères ayant le score le plus haut).",
    "technique": {
      "nom": "La source",
      "effet": "Une fois par jour, le personnage peut puiser dans sa Réserve personnelle de Points de Magie pour soigner des blessures, à raison d'une case de blessure par Point de Magie. Les points dépensés de cette façon ne peuvent être regagnés avant le prochain lever du soleil, quel que soit le moyen utilisé (méditation, rituel, etc.)."
    },
    "note": "À ce Statut, les mages peuvent tenter de devenir Maîtres de la Sphère ou de la Discipline dont ils ont acquis la maîtrise parfaite (Grand Maître du Feu ou des Rituels, par exemple). Comme chez les combattants, il n'existe qu'un seul Grand Maître reconnu pour chaque Sphère et chaque Discipline parmi l'ensemble des Grands Maîtres."
  },
  {
    "caste": "mage",
    "niveau": 1,
    "nom": "Apprenti noir",
    "requis": "une Sphère ou une Discipline à 4, Mental à 4, 10 points dans les Compétences de magie",
    "benefice": "Le personnage peut lire les runes magiques et reconnaître les domaines d'influence des mages grâce à leurs couleurs.",
    "technique": {
      "nom": "La matière",
      "effet": "Pour chaque Sphère qu'il maîtrise, le personnage peut faire apparaître, une fois par jour, un petit volume d'élément qu'il pourra ensuite façonner, orienter ou projeter à sa guise. Il peut s'agir d'une petite flamme, d'une poignée de terre, d'un litre d'eau pure, etc."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "mage",
    "niveau": 2,
    "nom": "Initié noir",
    "requis": "une Sphère ou une Discipline à 5, Intelligence à 6, 20 points dans les Compétences de magie",
    "benefice": "En réussissant un jet de Mental + Connaissance de la magie Difficulté 15, le personnage peut reconnaître un sortilège lancé par un autre mage. Si ce sortilège utilise sa Sphère privilégiée, la Difficulté de ce sort est réduite de 5.",
    "technique": {
      "nom": "L'esprit",
      "effet": "Chaque jour, le personnage dispose de deux Niveaux de Réussite gratuits qu'il peut utiliser pour augmenter les effets de n'importe quel sortilège (portée, dommages, précision, etc.). Ces bonus peuvent s'appliquer sur deux sortilèges différents ou pour améliorer deux effets d'un même sortilège. S'ils ne sont pas dépensés, ils sont tous simplement perdus."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "mage",
    "niveau": 3,
    "nom": "Mage noir",
    "requis": "une Sphère ou une Discipline à 7, Mental à 6, 30 points dans les Compétences de magie",
    "benefice": "Le personnage est désormais capable de concevoir ses propres sortilèges et de rédiger des parchemins magiques.",
    "technique": {
      "nom": "La volonté",
      "effet": "En dépensant 2 Points de Maîtrise et 2 Points de Magie, le personnage peut lancer et conserver un dé supplémentaire pour effectuer n'importe quel jet de Discipline magique. Ce dé neutre n'est pas concerné par la règle des Tendances."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "mage",
    "niveau": 4,
    "nom": "Grand Mage noir",
    "requis": "une Sphère ou une Discipline à 8, Intelligence à 8, 50 points dans les Compétences de magie",
    "benefice": "Le personnage ajoute le niveau de chacune de ses Sphères à tous ses jets de défense contre des sortilèges utilisant la Sphère correspondante.",
    "technique": {
      "nom": "La flamme",
      "effet": "Une fois par combat, le personnage peut lancer un sortilège de Magie instinctive sans dépenser aucun Point de Magie."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "mage",
    "niveau": 5,
    "nom": "Grand Maître noir",
    "requis": "une Sphère ou une Discipline à 10, Mental à 8, 70 points dans les Compétences de magie",
    "benefice": "Le personnage est immunisé aux effets des sortilèges de niveaux 1 et 2 de sa Sphère privilégiée.",
    "technique": {
      "nom": "La source noire",
      "effet": "Une fois par jour, le mage noir peut puiser dans sa Réserve personnelle de Points de Magie pour infliger des blessures, à raison d'une égratignure pour deux Points de Magie. Les points utilisés de cette manière ne peuvent être regagnés avant le prochain coucher de soleil - quel que soit le moyen utilisé (méditation, rituel, etc.)."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "prodige",
    "niveau": 1,
    "nom": "Prodige",
    "requis": "Tendance Dragon à 3, Empathie à 4",
    "benefice": "Le personnage est capable de communiquer par télépathie avec n'importe quelle créature draconique et peut développer une Spécialisation de son choix.",
    "technique": {
      "nom": "La source du rêve",
      "effet": "Une fois par jour, en imposant ses mains sur les plaies, le personnage peut soigner toutes les blessures légères d'un être humain ou d'un animal. Aucun jet n'est nécessaire, mais il faut quelques minutes avant que les maux ne disparaissent totalement."
    },
    "note": ""
  },
  {
    "caste": "prodige",
    "niveau": 2,
    "nom": "Prodige",
    "requis": "40 points dans les Compétences, tous les Attributs Majeurs à 4, Tendance Dragon à 3, Tendance Fatalité à 0",
    "benefice": "Du moment qu'il peut plonger son regard dans les yeux d'un être vivant, le personnage peut définir avec précision la valeur de sa Tendance Dragon. Aucun jet n'est nécessaire, mais le personnage doit pouvoir établir un contact visuel suffisant.",
    "technique": {
      "nom": "Le feu intérieur",
      "effet": "Une fois par tour, lorsqu'il combat à mains nues ou avec une arme contondante, le personnage peut ajouter le triple de la valeur de sa Tendance Dragon aux dommages d'une de ses attaques."
    },
    "note": ""
  },
  {
    "caste": "prodige",
    "niveau": 3,
    "nom": "Prodige",
    "requis": "60 points dans les Compétences, tous les Attributs Majeurs à 5, Tendance Dragon à 4, Tendances Homme et Fatalité à 0",
    "benefice": "Lorsqu'il est confronté à un dragon, le personnage est toujours capable de déterminer avec précision sa tranche d'âge, sa lignée et ses principaux traits de caractère. Si le dragon est sous forme humaine, le personnage doit effectuer un jet de Mental + Empathie contre une Difficulté de 15 pour comprendre.",
    "technique": {
      "nom": "La clarté de l'esprit",
      "effet": "Chaque fois qu'il est victime d'un sort offensif, le personnage peut tenter de résister à tous les effets magiques, sur un jet de Mental + Volonté contre une Difficulté de 10 + 5 par niveau du sort."
    },
    "note": ""
  },
  {
    "caste": "prodige",
    "niveau": 4,
    "nom": "Prodige",
    "requis": "80 points dans les Compétences, tous les Attributs Majeurs à 6, Tendance Dragon à 4, Tendances Homme et Fatalité à 0*",
    "benefice": "Porteur de l'héritage de Solyr, le premier Prodige, le personnage est à ce point respecté qu'aucun dragon n'ose plus s'attaquer physiquement à lui — excepté les fils de Kalimsshar. Cette relative « immunité » n'exclut pas le fait qu'un dragon tente de lui nuire, de façon beaucoup plus subtile, ou de s'en prendre à ses compagnons.",
    "technique": {
      "nom": "Le cycle primordial",
      "effet": "En dépensant définitivement 1 point de Résistance ou de Volonté, le personnage peut (se) faire repousser miraculeusement un membre détruit ou coupé. Il est également possible de faire repousser une tête de cette façon."
    },
    "note": "Pour prétendre à ce Statut, le personnage ne doit posséder aucun cercle noirci dans ces deux Tendances."
  },
  {
    "caste": "prodige",
    "niveau": 5,
    "nom": "Prodige",
    "requis": "120 points dans les Compétences, tous les Attributs Majeurs à 7, Tendance Dragon à 5, Tendances Homme et Fatalité à 0*",
    "benefice": "Une fois par jour, en procédant à une méditation collective, le personnage peut effacer tous ses cercles de Tendance Dragon pour réduire à zéro la Tendance Homme ou Fatalité d'un individu consentant.",
    "technique": {
      "nom": "Le serment de la Terre",
      "effet": "En perdant définitivement 1 Point de Tendance Dragon, le personnage peut détruire une créature vivante corrompue par Kalimsshar ou l'Humanisme, qu'il s'agisse d'un être humain, d'un monstre ou d'un dragon. Le Prodige doit impérativement établir un contact physique avec la créature visée. Une fois dépensé, le Point de Tendance ne peut être regagné qu'au prix de longues quêtes et d'épreuves draconiques supervisées par un fils de Heyra, ou le dragon auquel est lié le personnage."
    },
    "note": "Pour prétendre à ce Statut, le personnage ne doit posséder aucun cercle noirci dans ces deux Tendances."
  },
  {
    "caste": "protecteur",
    "niveau": 1,
    "nom": "Soldat",
    "requis": "une Compétence d'arme à 5, Lois à 3, Physique à 4, Tendance Dragon à 2",
    "benefice": "Le personnage peut porter un bouclier dragon et développer une Spécialisation de Combat.",
    "technique": {
      "nom": "L'écaille du dragon",
      "effet": "Si son jet de parade au bouclier est réussi contre la Difficulté de base, le personnage gagne automatiquement un Niveau de Réussite supplémentaire."
    },
    "note": ""
  },
  {
    "caste": "protecteur",
    "niveau": 2,
    "nom": "Lieutenant",
    "requis": "une Compétence d'arme à 6, Lois à 6, 30 points dans les Compétences de Combat, 15 points dans les Compétences d'Influence, Maîtrise à 4, Tendance Dragon à 3, 2 Privilèges de caste",
    "benefice": "Le personnage peut donner des ordres aux protecteurs de Statut inférieur et demander l'octroi d'hommes de troupe pour effectuer des missions précises. Le nombre maximum de renforts est égal à deux fois la Compétence Commandement du personnage, et il ne peut s'agir que de protecteurs de Statut strictement inférieur.",
    "technique": {
      "nom": "La cuirasse du dragon",
      "effet": "Chaque fois qu'il effectue une parade au bouclier, le personnage peut dépenser des Points de Maîtrise APRÈS son jet pour réussir sa défense, mais ne peut obtenir au maximum qu'autant de NR que l'attaquant."
    },
    "note": ""
  },
  {
    "caste": "protecteur",
    "niveau": 3,
    "nom": "Capitaine",
    "requis": "une Compétence d'arme à 7, Commandement à 5, 50 points dans les Compétences Physiques, 20 points dans les Compétences d'Influence, Maîtrise à 5, Tendance Dragon à 3, Tendances Homme et Fatalité à 2, 4 Privilèges de caste",
    "benefice": "Le personnage est autorisé à prendre les mesures qu'il juge nécessaires pour faire respecter les Lois draconiques au sein d'une cité.",
    "technique": {
      "nom": "Le souffle du dragon",
      "effet": "Lorsque le personnage choisit le dé du Dragon au cours d'un combat, il gagne automatiquement un jet supplémentaire, et ce quelle que soit l'action, si son jet est réussi."
    },
    "note": ""
  },
  {
    "caste": "protecteur",
    "niveau": 4,
    "nom": "Commandeur",
    "requis": "une Compétence d'arme à 8, Lois à 8, Commandement à 7, Maîtrise à 6, Tendance Dragon à 4, Tendances Homme et Fatalité à 0",
    "benefice": "Le personnage est chargé de l'autorité draconique et peut faire appliquer la loi sur l'ensemble de Kor. De plus, lorsqu'il prend le commandement d'une unité, tous les hommes qui suivent ses ordres gagnent un bonus de 2 à toutes leurs actions de combat. Ce bonus n'est applicable que si le personnage participe activement au combat.",
    "technique": {
      "nom": "Le sang du dragon",
      "effet": "Deux fois par jour, le personnage peut effectuer un jet d'Empathie + 1D10 contre une Difficulté de 0 pour guérir une case de blessure (au choix) par NR, à lui ou à une cible de son choix, tant que cette dernière peut entendre ses exhortations et ses encouragements."
    },
    "note": ""
  },
  {
    "caste": "protecteur",
    "niveau": 5,
    "nom": "Commandeur-dragon",
    "requis": "Commandement à 10, Lois à 10, Maîtrise à 9, Tendance Dragon à 5, 6 Privilèges de caste",
    "benefice": "L'importance du personnage aux yeux de Brorne lui permet de monter n'importe quel dragon de pierre à qui il en fait la demande, du moment que la raison de cette demande est fondée. S'il participe à une bataille à dos de dragon, tous les hommes qui sont sous son commandement gagnent un bonus de 3 à leurs actions de combat.",
    "technique": {
      "nom": "Le don draconique",
      "effet": "En dépensant définitivement 1 point de Résistance, le personnage peut rappeler à la vie n'importe quel être humain possédant au moins 3 en Tendance Dragon."
    },
    "note": ""
  },
  {
    "caste": "protecteur",
    "niveau": 1,
    "nom": "Soldat noir",
    "requis": "20 points dans les Compétences de Combat, Physique à 3",
    "benefice": "Le personnage peut porter un bouclier dragon et développer une spécialisation de Combat.",
    "technique": {
      "nom": "L'écaille du dragon",
      "effet": "Si son jet de parade au bouclier est réussi contre la Difficulté de base, le personnage gagne automatiquement un Niveau de Réussite supplémentaire."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "protecteur",
    "niveau": 2,
    "nom": "Lieutenant noir",
    "requis": "30 points dans les Compétences de Combat, 15 points dans les Compétences d'Influence",
    "benefice": "Le personnage peut donner des ordres aux protecteurs de Statut inférieur et demander l'octroi d'hommes de troupe pour effectuer des missions précises. Le nombre maximum de ces renforts est égal à deux fois la Compétence Commandement du personnage, et il ne peut s'agir que de protecteurs de Statut strictement inférieur.",
    "technique": {
      "nom": "La cuirasse du dragon",
      "effet": "Chaque fois qu'il effectue une parade au bouclier, le personnage peut dépenser des Points de Maîtrise APRÈS son jet pour réussir sa défense."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "protecteur",
    "niveau": 3,
    "nom": "Capitaine noir",
    "requis": "40 points dans les Compétences de Combat, 25 points dans les Compétences d'Influence, avoir résolu une situation délicate (en combat ou par action sociale)",
    "benefice": "Le personnage est autorisé à prendre les mesures qu'il juge nécessaires pour faire respecter les Lois draconiques au sein d'une cité.",
    "technique": {
      "nom": "Le souffle du dragon noir",
      "effet": "Lorsque le personnage choisit le dé de la Fatalité au cours d'un combat, il gagne automatiquement un Niveau de Réussite supplémentaire, et ce, quelle que soit l'action, si son jet est réussi."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "protecteur",
    "niveau": 4,
    "nom": "Commandeur noir",
    "requis": "50 points dans les Compétences de Combat, 40 points dans les Compétences Sociales, avoir commandé avec succès un bataillon de 200 hommes minimum",
    "benefice": "Le personnage est investi de l'autorité de Kalimsshar et peut faire appliquer sa loi sur l'ensemble du Royaume de Kor. De plus, lorsqu'il prend le commandement d'une unité, tous les hommes qui suivent ses ordres gagnent un bonus de 2 à toutes leurs actions de combat. Ce bonus n'est applicable que si le personnage participe activement au combat.",
    "technique": {
      "nom": "Le sang du dragon noir",
      "effet": "Le protecteur noir peut prendre sur lui les blessures de tout être vivant. Il peut diminuer chaque blessure d'un seuil par Niveau de Réussite sur un jet de Physique + Volonté Difficulté 10. Il lui est impossible de transférer une case de Mort."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "protecteur",
    "niveau": 5,
    "nom": "Dragon noir",
    "requis": "60 points dans les Compétences de Combat, 50 points dans les Compétences Sociales, avoir commandé avec succès une compagnie de 1000 hommes minimum",
    "benefice": "Le protecteur noir jouit d'une telle réputation que tous ses adversaires (au sens large) subissent en sa présence un malus de -3 pour chaque action agressive dirigée contre lui (attaques physiques, magiques, sociales, etc.).",
    "technique": {
      "nom": "Réveil d'entre les morts",
      "effet": "En dépensant définitivement un Point de Résistance, le protecteur noir peut transformer en mort asservi n'importe quel cadavre « frais » d'être humain (moins d'une semaine). Voir le sort Servitude de l'Ombre pour les caractéristiques de ce serviteur."
    },
    "note": "",
    "darkOrders": true
  },
  {
    "caste": "voyageur",
    "niveau": 1,
    "nom": "Marcheur",
    "requis": "six Compétences à 5, tous les Attributs Majeurs à 4, Chance à 2",
    "benefice": "S'il dispose d'une carte, le personnage peut déterminer le meilleur itinéraire pour relier deux points, estimer la durée du voyage et la présence possible d'auberges et de haltes. Le personnage peut développer une Spécialisation de Mouvement ou de Théorie.",
    "technique": {
      "nom": "À la croisée des chemins",
      "effet": "En réussissant un jet de Mental + Empathie contre une Difficulté de 10, le personnage peut comprendre le sens général de n'importe quelle phrase prononcée en langue inconnue. De plus, en réussissant un second jet, identique, il peut faire comprendre quelques mots à son interlocuteur et échanger de brèves informations."
    },
    "note": ""
  },
  {
    "caste": "voyageur",
    "niveau": 2,
    "nom": "Pisteur",
    "requis": "huit Compétences à 5, Social et Mental à 4, Chance à 3, 2 Privilèges de caste",
    "benefice": "Du moment qu'il a déjà visité un endroit ou emprunté une route, le personnage est capable de s'y repérer sans aucun risque de se perdre — les conditions de voyage extrêmes ne feront que ralentir sa progression.",
    "technique": {
      "nom": "Porté par le vent",
      "effet": "En dépensant tous ses Points de Chance restants (minimum 1), le personnage peut se jeter à terre et éviter n'importe quelle attaque. La Difficulté de toutes ses actions pour le tour suivant sera augmentée de 10 et le personnage ne pourra regagner aucun Point de Chance durant le reste du combat."
    },
    "note": ""
  },
  {
    "caste": "voyageur",
    "niveau": 3,
    "nom": "Voyageur",
    "requis": "une Compétence à 5 dans chacune des huit catégories, tous les Attributs Majeurs à 4, Empathie à 4, Chance à 5, 3 Privilèges de caste",
    "benefice": "Chaque fois qu'il entre en territoire inconnu (cité, région, fleuve, etc.), le personnage comprend d'instinct certaines caractéristiques propres à ce lieu. Sur un jet de Mental + Empathie contre une Difficulté de 5, il peut apprendre une information par NR (type de gouvernement, présence de dragons, cavités souterraines, etc.). Ce bénéfice ne peut être utilisé que pour des zones géographiques relativement vastes, et non des habitations ou des structures réduites.",
    "technique": {
      "nom": "Projectile cardinal",
      "effet": "Une fois par tour, s'il utilise une arme de distance (ou un ou plusieurs projectiles), le personnage peut renoncer à ses actions pour ne lancer qu'un seul projectile, dont les dommages seront doublés. Pour bénéficier de cet avantage, le personnage doit annoncer l'utilisation de sa Technique avant de déterminer son Initiative. Il conserve ensuite ses dés d'actions devant lui jusqu'à ce qu'il décide de lancer son projectile. Aucune action de défense n'est possible durant ce tour."
    },
    "note": ""
  },
  {
    "caste": "voyageur",
    "niveau": 4,
    "nom": "Solitaire",
    "requis": "80 points dans les Compétences, deux Attributs Majeurs à 6, Empathie à 6, Chance à 6, 5 Privilèges de caste",
    "benefice": "Le personnage est tellement habitué aux voyages que sa présence n'est plus considérée comme une menace par les animaux sauvages, qui ne l'attaquent plus. Au sein d'un groupe, la présence du personnage suffira à tenir en respect des prédateurs et des meutes. Cet avantage ne concerne pas les créatures magiques et/ou intelligentes.",
    "technique": {
      "nom": "Le couvert de la nuit",
      "effet": "Avec les éléments de décor environnants, le personnage peut se rendre si discret que nul ne remarquera sa présence. S'il reste immobile, aucun jet n'est nécessaire. S'il se déplace, sa progression est limitée à sa Coordination en mètres par tour et tous les individus présents dans un rayon de 15 mètres ont droit à un jet de Mental + Perception contre une Difficulté de 20 pour tenter de repérer sa présence. Ce jet doit être effectué à chaque tour où le personnage se déplace, et sa Difficulté peut être augmentée ou diminuée de 5 en fonction du décor. Le personnage est immédiatement repéré s'il effectue une action agressive ou bruyante, mais s'il parvient à moins de 5 mètres d'un adversaire, il peut porter une attaque dont la Difficulté sera réduite de 10. Aucune défense n'est alors possible."
    },
    "note": ""
  },
  {
    "caste": "voyageur",
    "niveau": 5,
    "nom": "Orphelin",
    "requis": "100 points dans les Compétences, tous les Attributs Majeurs à 7, Empathie à 8, Chance à 10",
    "benefice": "Le personnage ne dort jamais que d'un œil, mais son sommeil est incroyablement réparateur. Le moindre bruit suffit à le réveiller et une simple impression de danger mettra instantanément ses sens en alerte. Après une nuit de sommeil complète, le personnage peut dépenser des Points de Chance pour effacer autant de cases de blessure de n'importe quel type. Ces Points de Chance ne peuvent être regagnés avant d'avoir passé une seconde nuit de sommeil.",
    "technique": {
      "nom": "L'œil du fou",
      "effet": "Sans modifier son apparence, le personnage est capable de tromper n'importe quel interlocuteur humain en se faisant passer pour un individu qu'il connaît, ou qu'il invente. La victime de l'illusion est persuadée de faire face à l'homme ou à la femme incarnée par le personnage. Aucun jet ne peut permettre de deviner la supercherie."
    },
    "note": ""
  }
];
