// GENERATED by scripts/build-catalogs.ts from data-src/traits.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { TraitPreset } from './trait-catalog';

export const TRAIT_CATALOG_DATA: TraitPreset[] = [];
