// GENERATED by scripts/build-catalogs.ts from data-src/weapons.csv — DO NOT EDIT.
// Edit the CSV (Excel, séparateur « ; ») then run: bun run build:catalogs
import type { WeaponPreset } from './weapon-catalog';

export const WEAPON_CATALOG_DATA: WeaponPreset[] = [
  {
    "id": "epee-courte",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Épée courte",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 8 + 1D10",
      "prerequisites": "FOR 3",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-vulgaire",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Épée vulgaire",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-longue",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Épée longue",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 12 + 1D10",
      "prerequisites": "FOR 5",
      "initMelee": 2,
      "initCorpsACorps": -2,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-large",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Épée large",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 14 + 1D10",
      "prerequisites": "FOR 5",
      "initMelee": 0,
      "initCorpsACorps": -2,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-duel",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Épée de duel",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 8 + 1D10",
      "prerequisites": "FOR 4",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 6,
      "special": "Perforation",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "sabre",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Sabre",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 9 + 1D10",
      "prerequisites": "FOR 3, COO 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fauchard",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Fauchard",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 11 + 1D10",
      "prerequisites": "FOR 4, COO 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "cimeterre",
    "category": "Armes tranchantes",
    "hands": "Une main",
    "data": {
      "name": "Cimeterre",
      "skillName": "Armes tranchantes",
      "damage": "FOR + 13 + 1D10",
      "prerequisites": "FOR 5, COO 4",
      "initMelee": 1,
      "initCorpsACorps": -1,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-batarde",
    "category": "Armes tranchantes",
    "hands": "Deux mains",
    "data": {
      "name": "Épée bâtarde",
      "skillName": "Armes tranchantes",
      "damage": "(FOR * 2) + 8 + 1D10",
      "prerequisites": "FOR 5",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epee-deux-mains",
    "category": "Armes tranchantes",
    "hands": "Deux mains",
    "data": {
      "name": "Épée à deux mains",
      "skillName": "Armes tranchantes",
      "damage": "(FOR * 2) + 11 + 1D10",
      "prerequisites": "FOR 6",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "cimeterre-deux-mains",
    "category": "Armes tranchantes",
    "hands": "Deux mains",
    "data": {
      "name": "Cimeterre à deux mains",
      "skillName": "Armes tranchantes",
      "damage": "(FOR * 2) + 13 + 1D10",
      "prerequisites": "FOR 7, COO 5",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hachette",
    "category": "Armes de choc",
    "hands": "Une main",
    "data": {
      "name": "Hachette",
      "skillName": "Armes de choc",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 4, COO 4",
      "initMelee": -1,
      "initCorpsACorps": 1,
      "creationDifficulty": 10,
      "creationTime": 2,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hache",
    "category": "Armes de choc",
    "hands": "Une main",
    "data": {
      "name": "Hache",
      "skillName": "Armes de choc",
      "damage": "FOR + 15 + 1D10",
      "prerequisites": "FOR 5, COO 5",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hache-double",
    "category": "Armes de choc",
    "hands": "Une main",
    "data": {
      "name": "Hache double",
      "skillName": "Armes de choc",
      "damage": "FOR + 15 + 1D10",
      "prerequisites": "FOR 5, COO 6",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "pic-de-guerre",
    "category": "Armes de choc",
    "hands": "Une main",
    "data": {
      "name": "Pic de guerre",
      "skillName": "Armes de choc",
      "damage": "FOR + 6 + 1D10",
      "prerequisites": "FOR 3, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 1,
      "creationDifficulty": 10,
      "creationTime": 3,
      "special": "Armure divisée par 2",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "bec-de-corbin",
    "category": "Armes de choc",
    "hands": "Une main",
    "data": {
      "name": "Bec de corbin",
      "skillName": "Armes de choc",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 5, COO 7",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 4,
      "special": "Armure divisée par 2",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hache-justice",
    "category": "Armes de choc",
    "hands": "Deux mains",
    "data": {
      "name": "Hache de justice",
      "skillName": "Armes de choc",
      "damage": "(FOR * 2) + 15 + 1D10",
      "prerequisites": "FOR 6, COO 4",
      "initMelee": -2,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hache-deux-mains",
    "category": "Armes de choc",
    "hands": "Deux mains",
    "data": {
      "name": "Hache à deux mains",
      "skillName": "Armes de choc",
      "damage": "(FOR * 2) + 16 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": -2,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hache-double-deux-mains",
    "category": "Armes de choc",
    "hands": "Deux mains",
    "data": {
      "name": "Hache double à deux mains",
      "skillName": "Armes de choc",
      "damage": "(FOR * 2) + 17 + 1D10",
      "prerequisites": "FOR 7, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "pioche-guerre",
    "category": "Armes de choc",
    "hands": "Deux mains",
    "data": {
      "name": "Pioche de guerre",
      "skillName": "Armes de choc",
      "damage": "(FOR * 2) + 12 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "Armure divisée par 2",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "gourdin",
    "category": "Armes contondantes",
    "hands": "Une main",
    "data": {
      "name": "Gourdin",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 2) + 1D10",
      "prerequisites": "FOR 3",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 0,
      "creationTime": 0,
      "special": "+10 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "gourdin-ferre",
    "category": "Armes contondantes",
    "hands": "Une main",
    "data": {
      "name": "Gourdin ferré",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 2) + 2 + 1D10",
      "prerequisites": "FOR 4",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "+5 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "masse-armes",
    "category": "Armes contondantes",
    "hands": "Une main",
    "data": {
      "name": "Masse d'armes",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 2) + 4 + 1D10",
      "prerequisites": "FOR 4",
      "initMelee": 0,
      "initCorpsACorps": -1,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "masse-ailettes",
    "category": "Armes contondantes",
    "hands": "Une main",
    "data": {
      "name": "Masse à ailettes",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 2) + 6 + 1D10",
      "prerequisites": "FOR 5, COO 5",
      "initMelee": 0,
      "initCorpsACorps": -1,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "masse-pointes",
    "category": "Armes contondantes",
    "hands": "Une main",
    "data": {
      "name": "Masse à pointes",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 2) + 8 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "massue-ferree",
    "category": "Armes contondantes",
    "hands": "Deux mains",
    "data": {
      "name": "Massue ferrée",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 3) + 5 + 1D10",
      "prerequisites": "FOR 5",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 1,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "masse-deux-mains",
    "category": "Armes contondantes",
    "hands": "Deux mains",
    "data": {
      "name": "Masse à deux mains",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 3) + 7 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 6,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "marteau-deux-mains",
    "category": "Armes contondantes",
    "hands": "Deux mains",
    "data": {
      "name": "Marteau à deux mains",
      "skillName": "Armes contondantes",
      "damage": "(FOR * 3) + 9 + 1D10",
      "prerequisites": "FOR 7",
      "initMelee": -3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "Permet de renverser en mêlée",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fouet",
    "category": "Armes articulées",
    "hands": "Une main",
    "data": {
      "name": "Fouet",
      "skillName": "Armes articulées",
      "damage": "FOR",
      "prerequisites": "COO 7",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 6,
      "special": "Ne peut parer ou être parée. Attaque d'entravement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "chaine",
    "category": "Armes articulées",
    "hands": "Une main",
    "data": {
      "name": "Chaîne",
      "skillName": "Armes articulées",
      "damage": "FOR + 2D10",
      "prerequisites": "FOR 4, COO 7",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 5,
      "special": "Ne peut parer ou être parée. Attaque d'entravement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fleau-leger",
    "category": "Armes articulées",
    "hands": "Une main",
    "data": {
      "name": "Fléau léger",
      "skillName": "Armes articulées",
      "damage": "(FOR*2) + 1+ 1D10",
      "prerequisites": "FOR 4, COO 6",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 6,
      "special": "-5 à la parade de l'adversaire",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fleau-triple",
    "category": "Armes articulées",
    "hands": "Une main",
    "data": {
      "name": "Fléau Triple",
      "skillName": "Armes articulées",
      "damage": "(FOR*2) + 3 + 1D10",
      "prerequisites": "FOR 6, COO 7",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 8,
      "special": "-8 à la parade de l'adversaire",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fleau-lourd",
    "category": "Armes articulées",
    "hands": "Une main",
    "data": {
      "name": "Fléau lourd",
      "skillName": "Armes articulées",
      "damage": "(FOR*2) + 5 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 10,
      "special": "-5 à la parade de l'adversaire",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fleau-paysan",
    "category": "Armes articulées",
    "hands": "Deux mains",
    "data": {
      "name": "Fléau paysan",
      "skillName": "Armes articulées",
      "damage": "(FOR*2) + 2 + 1D10",
      "prerequisites": "FOR 5, COO 5",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 2,
      "special": "-3 à la parade de l'adversaire et +5 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "fleau-a-deux-mains",
    "category": "Armes articulées",
    "hands": "Deux mains",
    "data": {
      "name": "Fléau à deux mains",
      "skillName": "Armes articulées",
      "damage": "(FOR*3) + 5 + 1D10",
      "prerequisites": "FOR 6, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 10,
      "special": "-5 à la parade de l'adversaire",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "poing-de-brorne",
    "category": "Armes articulées",
    "hands": "Deux mains",
    "data": {
      "name": "Poing de Brorne",
      "skillName": "Armes articulées",
      "damage": "(FOR*3) + 2D10",
      "prerequisites": "FOR 7,COO 7",
      "initMelee": -2,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 12,
      "special": "-5 à la parade de l'adversaire et permet de renverser en mêlée",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "double-epee",
    "category": "Armes doubles",
    "hands": "Une main",
    "data": {
      "name": "Double épée",
      "skillName": "Armes doubles",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 6, COO 7",
      "initMelee": 2,
      "initCorpsACorps": -2,
      "creationDifficulty": 20,
      "creationTime": 7,
      "special": "Enchainement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "lance-sabre",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Lance-sabre",
      "skillName": "Armes doubles",
      "damage": "FOR + 11 + 1D10",
      "prerequisites": "FOR 5, COO 6",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "baton-de-combat",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Bâton de combat",
      "skillName": "Armes doubles",
      "damage": "(FOR*2) + 1D10",
      "prerequisites": "COO 3",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 5,
      "creationTime": 1,
      "special": "+5 pour assomer, 2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "shaadukt",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Shaaduk't",
      "skillName": "Armes doubles",
      "damage": "(FOR*2) + 4 + 1D10",
      "prerequisites": "FOR 5, COO 6",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 8,
      "special": "+5 pour assomer, +5 pour déséquilibrer, 2 mains uniquement'",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "nirgak-zul",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Nirga'k Zûl",
      "skillName": "Armes doubles",
      "damage": "(FOR*2) + 6 + 1D10",
      "prerequisites": "FOR 5, COO 6",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "Enchainement, 2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "croc-a-chaine",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Croc à chaîne",
      "skillName": "Armes doubles",
      "damage": "FOR + 11 + 1D10",
      "prerequisites": "FOR 5, COO 7",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 8,
      "special": "-3 à la parade de l'adversaire, attaque d'entravement, 2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "double-chaine",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Double chaîne",
      "skillName": "Armes doubles",
      "damage": "(FOR*2) + 2D10",
      "prerequisites": "FOR 5, COO 8",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 9,
      "special": "-8 à la parade de l'adversaire, 0 dégats sur armure lourde, 2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "double-fleau-fleau-harmonie",
    "category": "Armes doubles",
    "hands": "Deux mains",
    "data": {
      "name": "Double fléau Fléau d'harmonie",
      "skillName": "Armes doubles",
      "damage": "(FOR*3) + 4 + 1D10",
      "prerequisites": "FOR 6, COO 7",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 8,
      "special": "-5 à la parade de l'adversaire, 2 mains uniquement",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "poing",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Poing",
      "skillName": "Corps à corps",
      "damage": "FOR + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 2,
      "creationDifficulty": 0,
      "creationTime": 0,
      "special": "+3 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "pieds",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Pieds",
      "skillName": "Corps à corps",
      "damage": "FOR + 2 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 1,
      "creationDifficulty": 0,
      "creationTime": 0,
      "special": "+3 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "gant-cloute",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Gant clouté",
      "skillName": "Corps à corps",
      "damage": "FOR + 1 + 1D11",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 1,
      "creationDifficulty": 10,
      "creationTime": 3,
      "special": "+3 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "gant-de-metal",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Gant de métal",
      "skillName": "Corps à corps",
      "damage": "FOR + 2 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 1,
      "creationDifficulty": 15,
      "creationTime": 6,
      "special": "+3 pour assomer",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "cestus",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Cestus",
      "skillName": "Corps à corps",
      "damage": "FOR + 4 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 2,
      "creationDifficulty": 10,
      "creationTime": 2,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "serpe",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Serpe",
      "skillName": "Corps à corps",
      "damage": "FOR + 5 + 1D10",
      "prerequisites": "",
      "initMelee": -1,
      "initCorpsACorps": -1,
      "creationDifficulty": 10,
      "creationTime": 3,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "couteau",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Couteau",
      "skillName": "Corps à corps",
      "damage": "FOR + 3 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 1,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "dague",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Dague",
      "skillName": "Corps à corps",
      "damage": "FOR + 6 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 1,
      "creationDifficulty": 10,
      "creationTime": 2,
      "special": "",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "dague-main-gauche",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Dague main gauche",
      "skillName": "Corps à corps",
      "damage": "FOR + 5 + 1D10",
      "prerequisites": "",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "+3 parade contre armes tranchantes à une main",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "katar",
    "category": "Armes de corps à corps",
    "hands": "Une main",
    "data": {
      "name": "Katar",
      "skillName": "Corps à corps",
      "damage": "FOR + 5 + 1D10",
      "prerequisites": "",
      "initMelee": -1,
      "initCorpsACorps": 2,
      "creationDifficulty": 15,
      "creationTime": 6,
      "special": "armures légères divisées par 2",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "lance-courte",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Lance courte",
      "skillName": "Armes d'hast",
      "damage": "FOR + 8 + 1D10",
      "prerequisites": "FOR 3 , COO 3",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 2,
      "special": "+3 maintien à distance",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "lance",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Lance",
      "skillName": "Armes d'hast",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 4 , COO 5",
      "initMelee": 5,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 2,
      "special": "+5 maintien à distance, contre-charge",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "epieu",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Epieu",
      "skillName": "Armes d'hast",
      "damage": "FOR + 12 + 1D10",
      "prerequisites": "FOR 5 , COO 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 2,
      "special": "+3 maintien à distance, contre-charge",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "vouge",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Vouge",
      "skillName": "Armes d'hast",
      "damage": "FOR + 11 + 1D10",
      "prerequisites": "FOR 5 , COO 4",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "+5 maintien à distance,contre-charge",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "hallebarde",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Hallebarde",
      "skillName": "Armes d'hast",
      "damage": "FOR + 11 + 1D10",
      "prerequisites": "FOR 5, COO 6",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "+4 maintien à distance,permet de déséquilibrer en mêlée",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "trident",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Trident",
      "skillName": "Armes d'hast",
      "damage": "FOR + 14 + 1D10",
      "prerequisites": "FOR 5 , COO 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "+3 maintien à distance,",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "pique",
    "category": "Armes d'hast",
    "hands": "Deux mains",
    "data": {
      "name": "Pique",
      "skillName": "Armes d'hast",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 6 , COO 5",
      "initMelee": 10,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 3,
      "special": "+1 maintien à distance, contre-charge",
      "rangeEffective": null,
      "rangeMax": null
    }
  },
  {
    "id": "bolas",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Bolas",
      "skillName": "Armes de jet",
      "damage": "0",
      "prerequisites": "PER 3, COO 6",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "Ne peut pas se parer, attaque d'entravement",
      "rangeEffective": "(FOR*2)",
      "rangeMax": "(FOR*4)"
    }
  },
  {
    "id": "pierre",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Pierre",
      "skillName": "Armes de jet",
      "damage": "FOR + 1D10",
      "prerequisites": "",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 0,
      "creationTime": 0,
      "special": "Ne peut pas se parer sauf bouclier",
      "rangeEffective": "FOR",
      "rangeMax": "(FOR*2)"
    }
  },
  {
    "id": "dards",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Dards",
      "skillName": "Armes de jet",
      "damage": "FOR + 1D10",
      "prerequisites": "PER 3, COO 4",
      "initMelee": 4,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 0.5,
      "special": "Ne peut ni se parer ni s'esquiver",
      "rangeEffective": "(FOR*2)",
      "rangeMax": "(FOR*3)"
    }
  },
  {
    "id": "poignards-de-lancer",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Poignards de lancer",
      "skillName": "Armes de jet",
      "damage": "FOR + 2 + 1D10",
      "prerequisites": "PER 4, COO 4",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 1,
      "special": "Ne peut ni se parer ni s'esquiver",
      "rangeEffective": "(FOR*2)",
      "rangeMax": "(FOR*3)"
    }
  },
  {
    "id": "couteau-etoile-zul",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Couteau étoile Zûl",
      "skillName": "Armes de jet",
      "damage": "(FOR*2) + 5 + 1D10",
      "prerequisites": "PER 4, COO 6",
      "initMelee": 2,
      "initCorpsACorps": 0,
      "creationDifficulty": 20,
      "creationTime": 8,
      "special": "Ne peut pas se parer sauf bouclier",
      "rangeEffective": "(FOR*3)",
      "rangeMax": "(FOR*5)"
    }
  },
  {
    "id": "hachette-jet",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Hachette",
      "skillName": "Armes de jet",
      "damage": "(FOR*2) + 1D10",
      "prerequisites": "PER 5, COO 4",
      "initMelee": 1,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 2,
      "special": "Ne peut pas se parer sauf bouclier",
      "rangeEffective": "(FOR*2)",
      "rangeMax": "(FOR*3)"
    }
  },
  {
    "id": "javelot",
    "category": "Armes de jet",
    "hands": "Une main",
    "data": {
      "name": "Javelot",
      "skillName": "Armes de jet",
      "damage": "(FOR*2) + 2 + 1D10",
      "prerequisites": "PER 6, COO 4",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "Ne peut pas se parer sauf bouclier",
      "rangeEffective": "(FOR*5)",
      "rangeMax": "(FOR*10)"
    }
  },
  {
    "id": "arc-commun",
    "category": "Armes à projectile",
    "hands": "Deux mains",
    "data": {
      "name": "Arc commun",
      "skillName": "Armes à projectiles",
      "damage": "FOR + 6 + 1D10",
      "prerequisites": "FOR 3 , PER 4",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 10,
      "special": "Attaque éclair, approvisionnement",
      "rangeEffective": "40",
      "rangeMax": "100"
    }
  },
  {
    "id": "arc-composite",
    "category": "Armes à projectile",
    "hands": "Deux mains",
    "data": {
      "name": "Arc composite",
      "skillName": "Armes à projectiles",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 6 , PER 4",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 15,
      "special": "Attaque éclair, approvisionnement",
      "rangeEffective": "60",
      "rangeMax": "200"
    }
  },
  {
    "id": "arc-long",
    "category": "Armes à projectile",
    "hands": "Deux mains",
    "data": {
      "name": "Arc long",
      "skillName": "Armes à projectiles",
      "damage": "FOR + 8 + 1D10",
      "prerequisites": "FOR 5 , PER 4",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 18,
      "special": "Attaque éclair, approvisionnement",
      "rangeEffective": "80",
      "rangeMax": "300"
    }
  },
  {
    "id": "fronde",
    "category": "Armes à projectile",
    "hands": "Une main",
    "data": {
      "name": "Fronde",
      "skillName": "Armes à projectiles",
      "damage": "10",
      "prerequisites": "PER 4, COO 6",
      "initMelee": -1,
      "initCorpsACorps": 0,
      "creationDifficulty": 15,
      "creationTime": 4,
      "special": "Attaque éclair, approvisionnement",
      "rangeEffective": "20",
      "rangeMax": "100"
    }
  },
  {
    "id": "sarbacane",
    "category": "Armes à projectile",
    "hands": "Deux mains",
    "data": {
      "name": "Sarbacane",
      "skillName": "Armes à projectiles",
      "damage": "1",
      "prerequisites": "",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "Attaque éclair, pas de dommage si armure",
      "rangeEffective": "20",
      "rangeMax": "20"
    }
  },
  {
    "id": "atlat",
    "category": "Armes à projectile",
    "hands": "Deux mains",
    "data": {
      "name": "Atlat",
      "skillName": "Armes à projectiles",
      "damage": "(FOR*2) + 1D10",
      "prerequisites": "PER 5, COO 5",
      "initMelee": 0,
      "initCorpsACorps": 0,
      "creationDifficulty": 10,
      "creationTime": 1,
      "special": "Attaque éclair, approvisionnement",
      "rangeEffective": "(FOR*4)",
      "rangeMax": "(FOR*6)"
    }
  },
  {
    "id": "arbalete-legere",
    "category": "Armes mécaniques",
    "hands": "Deux mains",
    "data": {
      "name": "Arbalète légère",
      "skillName": "Armes mécanique",
      "damage": "FOR + 6 + 1D10",
      "prerequisites": "FOR 4",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 10,
      "special": "Attaque éclair, armure divisée par 2, réarmement 2",
      "rangeEffective": "40",
      "rangeMax": "140"
    }
  },
  {
    "id": "arbalete-moyenne",
    "category": "Armes mécaniques",
    "hands": "Deux mains",
    "data": {
      "name": "Arbalète moyenne",
      "skillName": "Armes mécanique",
      "damage": "FOR + 8 + 1D10",
      "prerequisites": "FOR 5",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 12,
      "special": "Attaque éclair, armure divisée par 2, réarmement 3",
      "rangeEffective": "50",
      "rangeMax": "200"
    }
  },
  {
    "id": "arbalete-lourde",
    "category": "Armes mécaniques",
    "hands": "Deux mains",
    "data": {
      "name": "Arbalète lourde",
      "skillName": "Armes mécanique",
      "damage": "FOR + 10 + 1D10",
      "prerequisites": "FOR 6",
      "initMelee": 3,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 15,
      "special": "Attaque éclair, armure divisée par 2, réarmement 4",
      "rangeEffective": "80",
      "rangeMax": "380"
    }
  },
  {
    "id": "lance-harpon",
    "category": "Armes mécaniques",
    "hands": "Deux mains",
    "data": {
      "name": "Lance-harpon",
      "skillName": "Armes mécanique",
      "damage": "25",
      "prerequisites": "FOR 6",
      "initMelee": 4,
      "initCorpsACorps": 0,
      "creationDifficulty": 25,
      "creationTime": 15,
      "special": "Attaque éclair, armure divisée par 2, réarmement 3",
      "rangeEffective": null,
      "rangeMax": null
    }
  }
];
